"""v79 (2026-09-17): wave three of the rewrite — Knowledge and Home finished, plus money.run and money.invest.
Ladders to tools/areas/BRIEF.md (worldwide rule and
`who` label included), drafted by writers J–O, every rung read. Run after apply_v78.py: python3 tools/areas/apply_v79.py
"""
import json, os, re, sys
HERE = os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0, os.path.join(HERE, '..', 'health'))
from lib import load, save

IDS = ['words.read', 'words.hand', 'words.poems', 'words.lang', 'words.irish', 'words.sign',
       'mind.tables', 'mind.mental', 'mind.memory', 'mind.puzzles', 'mind.codes', 'mind.cube',
       'mind.chess', 'classic.logic', 'classic.question', 'classic.roots', 'money.run', 'money.invest',
       'beauty.look', 'beauty.shapes', 'beauty.symmetry', 'beauty.proportion', 'beauty.arches', 'home.tools',
       'order.desk', 'order.wardrobe', 'order.broken', 'order.giving', 'order.digital', 'order.forgotten',
       'order.keeping', 'home.keep', 'home.firstaid', 'home.safe', 'food.grow', 'food.preserve']
FIX = [  # the read
 ('home.firstaid', 11, 'test', 'Learn the four signs of a stroke, and say them to somebody else.', 'Learn the signs of a stroke, and say them to somebody else.'),   # FAST is three signs and the time
]
KINDS = {'skill', 'attention', 'courage', 'kindness'}; CTX = {'room', 'home', 'kit', 'with', 'out', 'long'}
BAN = ['£', 'Northern Ireland', ' NI ', 'Belfast', 'ring 999', 'call 999', '999 operator', 'Met Office', 'NHS', 'chippy', 'postie', 'car boot', 'finish line']

d = load()
where = {t['id']: (c, i) for c in d['categories'] for i, t in enumerate(c['tracks'])}
for tid in IDS:
    new = json.load(open(os.path.join(HERE, tid + '.json')))
    for (lid, n, f, old, rep) in FIX:
        if lid != tid: continue
        obj = new if n is None else new['steps'][n - 1]
        if old in obj[f]: obj[f] = obj[f].replace(old, rep)
        else: assert rep in obj[f], (tid, n, old)
    c, i = where[tid]; cur = c['tracks'][i]
    for k in ('id', 'size', 'strand'): assert new[k] == cur[k], (tid, k)
    for k in ('place', 'need', 'after', 'pic', 'warn'):
        if k in cur and k not in new: new[k] = cur[k]
    assert 12 <= len(new['steps']) <= 20 and new['about'].strip() and new['line'].strip(), tid
    new['who'] = {'Everybody from about six; a child and a grown-up side by side': 'From about six; a child and a grown-up side by side', 'Everybody from about eight; a child and a grown-up side by side': 'From about eight; a child and a grown-up side by side'}.get(new.get('who'), new.get('who'))
    assert new.get('who') and len(new['who']) <= 60, (tid, new.get('who'))
    blob = json.dumps(new, ensure_ascii=False)
    for b in BAN: assert b not in blob, (tid, b)
    for j, s in enumerate(new['steps'], 1):
        assert s['n'] == j and s['test'].strip() and len(s.get('note', '')) > 40, (tid, j)
        assert s['ctx'] in CTX and s['kind'] in KINDS, (tid, j)
        assert 'mins' not in s or j == 1 or (s.get('extra') and 10 <= s['mins'] <= 20), (tid, j)
    assert isinstance(new['steps'][0].get('mins'), int), tid
    c['tracks'][i] = new
save(d)
fm = os.path.join(HERE, '..', 'daily', 'first_mins.py'); s = open(fm).read()
for tid in IDS:
    m = where[tid][0]['tracks'][where[tid][1]]['steps'][0]['mins']
    s, k = re.subn(r"'%s': (None|\d+)" % re.escape(tid), "'%s': %d" % (tid, m), s); assert k == 1, tid
open(fm, 'w').write(s)
print('rewritten:', len(IDS), 'ladders,', sum(len(where[t][0]['tracks'][where[t][1]]['steps']) for t in IDS), 'rungs')

# the evening extras now live on the rewritten order ladders: regenerate order_extras.py from school.json,
# so re-running patch_v74 re-tags the right rungs with their current notes
d = load(); lines = ['"""Creating order rungs used as Today\'s extra (regenerated by apply_v79.py from school.json).', '(rung n, minutes, note). Doing one as an extra does NOT tick the rung."""', 'EXTRAS = {']
n_ex = 0
for c in d['categories']:
    for t in c['tracks']:
        ex = [s for s in t['steps'] if s.get('extra')]
        if not ex: continue
        lines.append(' %r: [' % t['id'])
        for s in ex: lines.append('  (%d, %d, %r),' % (s['n'], s['mins'], s['note'])); n_ex += 1
        lines.append(' ],')
lines.append('}')
open(os.path.join(HERE, '..', 'daily', 'order_extras.py'), 'w').write('\n'.join(lines) + '\n')
print('extras from ladders:', n_ex)
