# -*- coding: utf-8 -*-
"""The pushing and middle ladders, re-ordered and given a note each.
   Press-ups now END at thirty in one go (his call: significant, not overwhelming,
   and no equipment), and the line matches the last rung."""
import lib
d = lib.load()

lib.put(d, 'fit.pressup', name='Press-ups', size='months', line='From two to thirty in one go.',
        about=("Thirty press-ups in one go is a real undertaking and it is not an overwhelming one. It needs "
               "no equipment, no gym and no money, it takes about five minutes a session three times a week, "
               "and the whole path from two to thirty is a few simple steps repeated. Almost nobody who does "
               "the sets fails to get there. It is the clearest proof in the school that a thing you could "
               "not do last month is now yours."),
        rungs=[
 ("Do two proper press-ups. Hands on a table or a step if you need to.",
  'skill', 'room',
  ["Body one straight line from heels to head, hands a little wider than your shoulders.",
   "Chest down to a fist's width from the surface, elbows going back at forty-five degrees, then all the way up.",
   "Raise your hands until two are honest: table, then a chair, then a step, then the floor."],
  "Two real ones beat ten half ones and always will. If you are already past two on the floor, start at the rung that is actually hard for you and count the ones below as done."),
 ("Do five in a row at the height where five is hard.",
  'skill', 'room',
  ["Pick the height where the fifth one is a struggle — table, sofa arm, bottom step.",
   "Five with no rest at the top.",
   "Same depth every rep. When the depth goes, the set is over."],
  "The height is your dial. You lower it when five becomes easy, and every time you lower it you are lifting more of yourself."),
 ("Do ten in a row at that height.",
  'skill', 'room',
  ["Two seconds down, one second up, no bouncing off the bottom.",
   "If you stall at seven, rest ten seconds and finish — then go for ten unbroken next time.",
   "When ten is comfortable, drop the height one notch."],
  "Ten at a raised height is the strength that makes the first floor press-up possible. Do not skip ahead; people who do spend a month stuck at one."),
 ("Do one press-up on the floor, chest all the way down.",
  'skill', 'room',
  ["Hands under your shoulders, heels to head in one line, backside squeezed.",
   "Down until your chest is a fist's width off the floor, then all the way up.",
   "One. Properly. That is the whole rung."],
  "This is the moment people remember. If it will not come yet, go back a rung for a fortnight — the bottom step is not a failure, it is the training."),
 ("Do three in a row on the floor.",
  'skill', 'room',
  ["Fresh, at the start of a session, not the end.",
   "No resting at the top. Three continuous.",
   "If you get two, do two, rest a minute, and do two more."],
  "From here on, every number is bought with sets on the days in between, not with heroics on the day."),
 ("Do five in a row on the floor.",
  'skill', 'room',
  ["Build it with three sets of three, twice a week, with a minute between sets.",
   "Then try five unbroken on a fresh day.",
   "Chest to the floor every single rep."],
  "Two to five is usually about a fortnight. This is also where the easiest mistake shows up: chasing the number and letting the depth go."),
 ("Do press-ups on three separate days in one week.",
  'attention', 'long',
  ["Monday, Wednesday, Friday, or whatever three days suit, with a day off between.",
   "Three or four sets each day, stopping two short of failure every set.",
   "Write the three days down and tick them off."],
  "This rung is the engine of the whole ladder. Everything from here is built on three sessions a week; without them the numbers stop moving at about eight."),
 ("Do eight in a row.",
  'skill', 'room',
  ["Sets of five on your three days, then go for eight on a fresh one.",
   "Breathe in on the way down, out on the way up.",
   "Do not let your hips lead. Shoulders and hips move together."],
  "If your back is sagging by the sixth, your middle is the limit, not your arms — squeeze your backside hard and the shape holds."),
 ("Do ten in a row.",
  'skill', 'room',
  ["Three sets of six or seven on your training days is what buys ten.",
   "Fresh, first thing in the session.",
   "Get it twice in one week before you call it yours."],
  "Ten proper press-ups is already more than most adults can do. It is also the halfway house: from here the method changes from more reps to harder reps."),
 ("Do five slowly — three seconds down, three seconds up.",
  'skill', 'room',
  ["Count it out. Three full seconds each way, no cheating at the top.",
   "Five of these is thirty seconds of unbroken work and it is brutal.",
   "If you collapse at four, that is the rung for another week."],
  "Time under strain is what actually builds muscle. This one rung is why your normal number jumps a fortnight later without you trying."),
 ("Do fifteen in a row.",
  'skill', 'room',
  ["Sets of ten on your three days, then fifteen fresh.",
   "Pace it — the first five should feel too slow.",
   "Depth to the last one or it does not count."],
  "The middle of a long set is where you find out whether you can stay calm while something is uncomfortable. That is a skill worth more than the press-ups."),
 ("Do thirty across one day, in as many sets as you like.",
  'skill', 'long',
  ["Five here, five there — every time you walk past a clear bit of floor.",
   "Spread them across the whole day. Nothing has to be hard.",
   "Count as you go so you know when you are done."],
  "Total volume is the quiet ingredient in all of this. A day of easy sets does more for next month's number than one heroic set does."),
 ("Do twenty in a row.",
  'skill', 'room',
  ["Build with three sets of thirteen to fifteen, twice a week.",
   "Fresh, first, with a proper warm-up: twenty squats and some arm swings.",
   "Twenty unbroken, chest to the floor."],
  "Twenty is two thirds of the way there, and it is the number where people start noticing your shoulders. Keep the depth honest and the last ten come faster than you expect."),
 ("Do ten with your feet up on a chair.",
  'skill', 'room',
  ["Feet on a chair or the second step, hands on the floor, one straight line.",
   "More weight goes through your arms, so ten here is worth about fifteen flat.",
   "Chest all the way down, every rep."],
  "This is how you keep getting stronger without weights: raise the feet instead of adding reps. It is also the fastest way to add five to your flat number."),
 ("Do press-ups every other day for a fortnight.",
  'attention', 'long',
  ["Seven sessions in fourteen days, three or four sets each, never to complete failure.",
   "Alternate: one day flat, next session feet up.",
   "Miss one and do it the next day rather than starting the fortnight again."],
  "Press-ups recover fast, which is why they take well to every other day where most training does not. This fortnight is usually worth five reps on its own."),
 ("Do twenty-five in a row.",
  'skill', 'room',
  ["Sets of eighteen to twenty on your training days.",
   "Slow the middle of the set down deliberately — rushing is what ends it early.",
   "Fresh, first thing, properly warmed up."],
  "Twenty-five is where the set becomes a mental job as much as a physical one. Pick a spot on the floor, breathe, and keep the rhythm identical from the first to the last."),
 ("Do fifty across one day, in as many sets as you like.",
  'skill', 'long',
  ["Ten sets of five, or five sets of ten, or anything in between.",
   "Spread across the whole day so nothing is ever hard.",
   "Count them and stop at fifty."],
  "The same trick as rung twelve with a bigger number. Do this in the week before you go for thirty and the thirty will feel lighter."),
 ("Do ten with your feet up on a chair, slowly — two seconds down, two up.",
  'skill', 'room',
  ["Feet up, flat hands, count the seconds out.",
   "Forty seconds of work. This is the hardest rung on the ladder.",
   "Nine honest ones beats ten with the last three rushed."],
  "If you can do this, thirty flat is already in you — it is now only a question of pacing the long set. This is the rung that quietly finishes the job."),
 ("Do thirty press-ups in one go.",
  'skill', 'room',
  ["Fresh, first thing, properly warmed up, on a day you have slept.",
   "Start slower than feels right. A steady rhythm all the way is what gets you past twenty-five.",
   "Chest to the floor every rep, no resting at the top.",
   "Missed at twenty-seven? That is a very good day. Go again in three days."],
  "That is the ladder. Thirty proper press-ups in one go, from two, with no equipment and no money spent — for most people about three months of a few minutes three times a week. Very few adults can do this."),
 ("Get somebody else from none to their first proper one.",
  'kindness', 'with',
  ["Start them on a table, exactly as you started.",
   "Five hard ones at the right height, three days a week. Lower the height when five is easy.",
   "Do the sessions with them rather than telling them about them.",
   "Warn them about depth before they learn it wrong."],
  "Teaching it is how you find out you actually know it, and the person you teach remembers it for the rest of their life. This costs you four weeks of five-minute sessions."),
])

lib.put(d, 'fit.squat', name='Squats', size='months', line='From ten to a hundred, and one on one leg.',
        about=("Legs are the muscles you use every single day and the first ones people lose. This ladder "
               "goes from ten honest squats to a hundred in one go and a squat on one leg, which almost "
               "nobody can do. It needs no equipment and no space beyond a patch of floor, and it is the "
               "quickest thing in the school to notice in ordinary life: stairs, hills, getting off the "
               "ground, carrying a child upstairs."),
        rungs=[
 ("Do ten squats with your heels flat and your thighs level at the bottom.",
  'skill', 'room',
  ["Feet about shoulder width, toes turned out a little, chest up.",
   "Sit back and down as if a chair were behind you, then stand all the way up.",
   "Heels lifting? Stand with them on a folded towel or a thin book and go again."],
  "Nearly everybody can already do ten of something they call a squat. The rung is ten where the thighs actually reach level — it is a different exercise and you will feel it."),
 ("Sit at the bottom of a squat for thirty seconds.",
  'skill', 'room',
  ["All the way down, heels flat, and stay there.",
   "Hold onto a door frame at first if you tip backwards.",
   "Relax into it rather than fighting it. Breathe."],
  "This is the position half the world rests in and most of us have lost. Getting it back is what makes every squat above it easy, so it comes early on purpose."),
 ("Do twenty in one go.",
  'skill', 'room',
  ["Steady pace from the first rep, not fast.",
   "Depth on the last one the same as the first.",
   "Knees push out over your toes, never caving inwards."],
  "Twenty is where you start breathing. Breathe out on the way up, every rep, and the whole thing gets easier."),
 ("Do thirty in one go.",
  'skill', 'room',
  ["Keep the last five as clean as the first five.",
   "Shaking legs are normal, caving knees are not.",
   "If depth goes at twenty-six, stop at twenty-six — that is the number."],
  "Thirty good squats a few days a week is enough on its own to change how stairs and hills feel. Most people notice that before they notice anything else."),
 ("Do squats on three separate days in one week.",
  'attention', 'long',
  ["Three sets each day, a day off between where you can.",
   "Never to complete failure — stop two or three short.",
   "Write the three days down and tick them off."],
  "This is the rung that makes the rest happen. Legs answer to how often, not how hard."),
 ("Sit at the bottom of a squat for a full minute.",
  'skill', 'room',
  ["Heels down, back reasonably straight, nothing to hold on to.",
   "Shift about, look around, breathe — it is a rest position, not a hold.",
   "Split into two thirties if you need to, then close the gap."],
  "A minute at the bottom without holding anything means your ankles and hips have opened up properly. From here the deep end of every squat stops being a fight."),
 ("Do fifty in one go.",
  'skill', 'room',
  ["Pace it like a run. The first twenty should feel too easy.",
   "Breathe in down, out up, every rep.",
   "Break it as twenty-five and twenty-five, then close the gap over a fortnight."],
  "Fifty in one go puts you past almost everybody you know. It is also the point where squats become a lungs exercise as much as a legs one."),
 ("Do ten slowly — four seconds down and four seconds up.",
  'skill', 'room',
  ["Count it out. Eighty seconds of unbroken work.",
   "No pause at the top to shake it off.",
   "If you cannot hold the count, do six and build up."],
  "Slow reps are where the strength comes from. Ten of these is harder than fifty normal ones and does more for your next number."),
 ("Do twenty holding something heavy at your chest.",
  'skill', 'kit',
  ["A full rucksack, a bag of potatoes, a water container, a small child who thinks it is a game.",
   "Held against your chest with both arms, elbows in.",
   "Nothing to hand? Fill a rucksack with books and wear it on your front."],
  "Adding weight is how a squat keeps getting harder once the reps get silly. Everything you need is already in the house and none of it costs anything."),
 ("Do seventy in one go.",
  'skill', 'room',
  ["Rhythm is everything now. Find one and do not change it.",
   "Small pauses at the top are allowed. Stopping is not.",
   "Depth to the last one."],
  "Seventy takes about two and a half minutes and it is mostly a test of whether you will keep going when it is boring and burning. That is the useful part."),
 ("Do a hundred across one day, split however you like.",
  'skill', 'long',
  ["Twenty every time you boil the kettle, or ten an hour.",
   "Nothing has to be hard. Spread them wide.",
   "Count as you go."],
  "Volume across a day builds legs beautifully and costs nothing in recovery. Do this in the week before you go for a hundred in one go."),
 ("Do ten jump squats, landing quietly.",
  'skill', 'room',
  ["Down to level, then jump, then land soft with bent knees and go straight into the next.",
   "Quiet landings are the rung. Loud landings mean you are crashing through your knees.",
   "Sore knees? Skip this rung and do thirty holding something heavy instead."],
  "Power is a different quality from strength and it is the first one that goes with age. Ten quiet jumps a week keeps it."),
 ("Do thirty holding something heavy.",
  'skill', 'kit',
  ["Same load as before, or heavier if twenty became easy.",
   "Depth first, number second.",
   "Set it down between sets rather than dropping it."],
  "Thirty loaded squats is a real bit of work and the closest this school gets to a gym without you ever going near one."),
 ("Do a hundred in one go.",
  'skill', 'room',
  ["Start absurdly slow. A hundred is about four minutes of work.",
   "Count in tens so the number stays small in your head.",
   "Breathe every rep and keep the depth honest to the end."],
  "A hundred unbroken squats is the far end of what reps alone can give you. From here the ladder turns to one leg, which is a harder and more useful thing."),
 ("Stand on one leg and go down as far as you can, holding onto a door frame.",
  'skill', 'room',
  ["One foot flat, the other leg held out in front, both hands on a door frame or a chair back.",
   "Down slowly, as far as you can control, then pull yourself back up.",
   "Use as much arm as you need at first."],
  "This is the start of the one-leg squat and it is more balance and ankle than strength. Nearly everybody tips over on the first attempt. That is the exercise."),
 ("Go halfway down on one leg without holding anything.",
  'skill', 'room',
  ["Arms straight out in front to balance, other leg held out.",
   "Halfway is thigh at about forty-five degrees. Come back up under control.",
   "Practise both legs — one will be noticeably worse and it needs the extra sets."],
  "Balance improves within days of trying this, and it is the single thing that keeps people on their feet in old age."),
 ("Go down on one leg onto a low seat and stand back up.",
  'skill', 'room',
  ["Sit down onto a low chair, stool or the second step with one leg out in front.",
   "Touch down, do not flop, then stand up on the same leg without rocking.",
   "Lower the seat over a few weeks until it is nearly the floor."],
  "The seat is your dial: the lower it goes, the closer you are to the full thing. This is exactly how the full one gets built."),
 ("Do one squat on one leg, all the way down and back up.",
  'skill', 'room',
  ["Other leg out in front and off the ground the whole way.",
   "All the way down, backside near the heel, then up without touching down.",
   "Hold a small weight out in front — it acts as a counterbalance and makes it easier."],
  "Very few adults can do this. It is the best single test there is of leg strength, balance and ankle range together, and it needs nothing but a floor."),
 ("Do three on one leg, on both legs.",
  'skill', 'room',
  ["Three in a row on each side, without touching down between them.",
   "The weaker side gets twice the practice until it catches up.",
   "Rest a full minute between sides."],
  "Three each side means it was not a fluke and both legs actually own it. That is the difference between a trick and a skill."),
 ("Do a hundred and fifty across one day, and walk properly the next.",
  'skill', 'long',
  ["Spread them right across the day in sets of fifteen or twenty.",
   "The rung is the next morning: stairs without wincing.",
   "Walk, and get your legs moving the day after rather than sitting still."],
  "Being able to do a big day's work and be fine the next morning is what fitness actually is. That is the ladder finished."),
])

lib.put(d, 'fit.plank', name='The plank', size='weeks', line='Twenty seconds, up to a solid two minutes and a side plank.',
        about=("The plank trains the part of you that stops your back hurting, and it needs a patch of floor "
               "and nothing else. This one stops at two minutes on purpose: past that it is a party trick, "
               "and a side plank or a one-foot plank buys far more for the same time. A few weeks of a "
               "minute a day is enough to feel it in how you stand."),
        rungs=[
 ("Hold a plank for twenty seconds with your hips level.",
  'skill', 'room',
  ["Elbows under your shoulders, forearms flat, feet back, one straight line from heels to head.",
   "Squeeze your backside and your stomach — that is what stops the sag.",
   "When the line breaks, the hold is over. That is your number."],
  "A sagging plank does nothing for you and can hurt your back. Twenty honest seconds is worth more than a minute of hanging off your spine."),
 ("Hold it for thirty seconds, breathing normally the whole time.",
  'skill', 'room',
  ["Timer on so you are not guessing.",
   "In through the nose, out through the mouth, steadily.",
   "If you are holding your breath, come down and try again."],
  "Breathing is the rung here, not the time. A plank you cannot breathe in is a plank you are bracing rather than holding."),
 ("Hold it for forty-five seconds.",
  'skill', 'room',
  ["Look at the floor just in front of your hands — your neck follows your back.",
   "Heels pushing back, crown of your head pushing forward.",
   "Break at thirty-five? Come down, rest a minute, do two more thirties."],
  "Little and often beats one long hold. Three short honest planks in a session build more than one sagging long one."),
 ("Hold it for one minute.",
  'skill', 'room',
  ["Pick a spot on the floor and stay with it.",
   "Squeeze harder rather than waiting it out — that is what buys the last fifteen seconds.",
   "Get it twice before you move on."],
  "A minute is the standard most people never need to beat for ordinary life. Everything past it is optional."),
 ("Hold a side plank for twenty seconds on each side.",
  'skill', 'room',
  ["On one forearm, elbow under your shoulder, feet stacked or one in front of the other.",
   "Hips lifted so you are a straight line from ankle to head.",
   "Knee down on the floor makes it easier while you learn it."],
  "The sides of your middle are what a normal plank misses entirely, and they are what actually hold your back steady when you carry something in one hand."),
 ("Hold a plank three separate times in one session, a minute each.",
  'skill', 'room',
  ["A minute on, a minute off, three times.",
   "The third one is the rung. The first two are the warm-up.",
   "Keep the shape identical in the third as in the first."],
  "Three honest minutes of work in five minutes of your life. This is the rung that makes the longer holds possible."),
 ("Hold it for ninety seconds.",
  'skill', 'room',
  ["Timer, level hips, steady breathing.",
   "Squeeze your backside hard — it is the one cue that works past a minute.",
   "Break at seventy? Hold seventy twice and come back in two days."],
  "Past a minute this becomes a test of staying calm while something is uncomfortable. That is worth practising for its own sake."),
 ("Hold a side plank for forty-five seconds on each side.",
  'skill', 'room',
  ["Feet stacked, hips high, top arm straight up or on your hip.",
   "The weaker side goes first and gets an extra set.",
   "Do not let your hips drift backwards — stay in one flat plane."],
  "One side being clearly worse is normal and worth knowing about. Give that side the extra work until they match."),
 ("Hold a plank with one foot off the floor, twenty seconds each side.",
  'skill', 'room',
  ["Normal plank, then lift one foot a few inches. Do not let your hips twist.",
   "Twenty seconds, swap, twenty seconds.",
   "Steady, small lift. This is about not moving, not about lifting high."],
  "Taking one point of contact away is how you make a plank harder without making it longer. Twenty seconds here is worth two minutes flat."),
 ("Hold it for two minutes.",
  'skill', 'room',
  ["Fresh, at the start of a session.",
   "Count in blocks of fifteen so the number stays small.",
   "The shape holds or it does not count."],
  "Two minutes is the honest end of the ordinary plank. If you have it, stop adding time and start taking feet off the floor instead."),
 ("Hold a side plank for a full minute on each side.",
  'skill', 'room',
  ["Both sides in the same session, a minute's rest between.",
   "Hips high the whole way.",
   "Lift the top leg for the last ten seconds once a minute is easy."],
  "A minute a side is a strong middle by any measure, and it shows up as carrying a bag on one shoulder without leaning."),
 ("Hold a two-minute plank with one foot off the floor for thirty seconds of it.",
  'skill', 'room',
  ["Two minutes in total: thirty normal, thirty left foot up, thirty right foot up, thirty normal.",
   "No twisting at the hips through the swaps.",
   "That is the end of this ladder."],
  "Harder, not longer, is the rule from here. If you want more, go to the sit-up ladder or hang from a bar and lift your knees."),
])

lib.save(d)
lib.report(d, ['fit.pressup','fit.squat','fit.plank'])
