# -*- coding: utf-8 -*-
"""The fitness spine: two twenty-rung programmes, the way Real food part one/two
   are the food spine. Everything here needs nothing but you, a floor, and a
   table or a windowsill. Part two ends by pointing at the deep ladders."""
import lib

d = lib.load()

lib.put(d, 'fit.body1', cid='fit', name='Getting strong, part one', size='months',
        strand='get-strong-outside',
        line='Three honest numbers, then a round of three moves, up to ten proper press-ups.',
        about=("This is the way in to everything physical in the school, and it needs nothing at all: "
               "no gym, no weights, no clothes you do not own, no money. Three moves — a squat, a press-up "
               "and a plank — done as one short round, a few days a week. You write down what you can do on "
               "day one, and at the end you write the same three numbers again underneath. Most people are "
               "somewhere around ten proper press-ups by the end of it, from nothing, in about three months. "
               "It takes six or seven minutes a session, and the reason it works is that it is small enough "
               "that you keep doing it."),
        rungs=[
 ("Write down three numbers: press-ups you can do in one go, squats in one go, seconds of a plank.",
  'attention', 'room',
  ["Do the three one after the other, with a good rest in between. This is a measurement, not a session.",
   "Knees on the floor counts for the press-ups. Stop each one when your shape goes, not when it burns.",
   "Write the three numbers down with today's date — paper, or a note on your phone.",
   "Put it where you will find it again in three months."],
  "This is the rung everything else is measured against, so be honest — nobody else ever sees it. If the answer is none, write nought. Nought is a perfectly good starting number and it does not stay nought."),
 ("Do ten squats with your heels flat on the floor and your thighs level at the bottom.",
  'skill', 'room',
  ["Feet about shoulder width, toes turned out a little.",
   "Sit back and down as if there were a chair behind you, chest up, heels glued down.",
   "Go until your thighs are level with the floor, then stand all the way up.",
   "If your heels lift, stand with them on a folded towel or a book and go again."],
  "This is the move most people already own and do badly: they stop halfway and lean forward. Ten honest ones beat thirty half ones. If ten is easy, do them slower — three seconds down — and count that as the rung."),
 ("Do five press-ups with your hands on a table or a windowsill.",
  'skill', 'room',
  ["Hands on the edge, a little wider than your shoulders, feet back so you are a straight plank.",
   "Lower your chest to the edge, elbows going back at about forty-five degrees, not out sideways.",
   "Push all the way up. Your hips move with your shoulders, never ahead of them.",
   "Too easy? Use something lower — the arm of a sofa, the third step of the stairs."],
  "Raised hands are not a lesser press-up, they are the same press-up with less of you to lift. Everybody starts at the height where five are honest. If five on a table is easy, find the height where five is hard and stay there."),
 ("Hold a plank for twenty seconds with your hips level.",
  'skill', 'room',
  ["Elbows under your shoulders, forearms flat, feet back, body in one straight line.",
   "Squeeze your backside and your stomach. That is what stops your hips sagging.",
   "Breathe normally the whole time. If you are holding your breath, come down.",
   "Twenty honest seconds. When your hips drop, the hold is over — that is the number."],
  "A sagging plank does nothing for you and hurts your back. Come down the second the line breaks. If twenty seconds is easy, hold it until it is not, and write down what you got."),
 ("Do all three back to back in one go: ten squats, five press-ups, twenty seconds of plank.",
  'skill', 'room',
  ["Squats first, straight into the press-ups, straight into the plank.",
   "Rest as long as you like between the three if you need to, but do all three in one sitting.",
   "It should take about two minutes.",
   "That is one round. The rest of this ladder is that round, getting heavier."],
  "Here is the whole programme in one rung. From now on there is nothing new to learn — the three moves you have just done are the three moves for the next three months. The work is turning up, not learning."),
 ("Do the round on three separate days in one week.",
  'attention', 'long',
  ["Three days, with a day off between them where you can — Monday, Wednesday, Friday is the classic.",
   "Same round each time: ten squats, five press-ups, twenty seconds of plank.",
   "Do it at the same point in the day, so it hangs off something you already do.",
   "Tick the three days off somewhere you can see them."],
  "This is the most important rung in the ladder and the least impressive. Three sessions in one week is the thing that turns an afternoon of good intentions into a body that changes. If you already train three days a week, do these rounds inside that and count it."),
 ("Do twenty squats in one go.",
  'skill', 'room',
  ["Same shape as before: heels down, thighs level, all the way up.",
   "Slow down rather than bounce when it gets hard near the end.",
   "If your form goes at seventeen, stop at seventeen and try again in two days.",
   "Add these to your round from now on."],
  "Your round is now twenty squats, five press-ups, twenty seconds. The numbers change, the round does not."),
 ("Do ten press-ups with your hands on a table.",
  'skill', 'room',
  ["Same table, same shape. Chest to the edge every time.",
   "Do not rush. Two seconds down, one second up.",
   "If you stall at seven, rest ten seconds and finish the last three. Next time, get all ten.",
   "Then lower the height: sofa arm, or a chair against a wall."],
  "Doubling the reps is easier than it sounds because your shape is now honest. If ten on a table came easily, move to something lower before you move on — the rung is ten hard ones, not ten easy ones."),
 ("Hold a plank for forty seconds.",
  'skill', 'room',
  ["Set a timer so you are not counting and guessing.",
   "Squeeze everything from your heels to your shoulders. A plank is a squeeze, not a hang.",
   "If the line breaks at thirty, come down, rest a minute, and hold twice more for twenty.",
   "Two short honest holds beat one long sagging one."],
  "Forty seconds is roughly where the plank stops being about your arms and starts being about your middle. If your lower back aches, your hips are too low — lift them a fraction and squeeze harder."),
 ("Do five press-ups with your hands on the bottom step of the stairs.",
  'skill', 'room',
  ["The lower your hands, the more of you there is to lift. The stairs are the dial.",
   "Same shape: straight line, elbows back, chest to the step.",
   "No stairs? Stack two thick books, or use the edge of a bed frame or a low sturdy box.",
   "When five on the bottom step is comfortable, the floor is next."],
  "This is the rung where the programme starts to feel like real training. You are not learning anything new — you are turning the dial down one notch and doing the same five."),
 ("Do two rounds back to back, with a minute between them.",
  'skill', 'room',
  ["Round one: twenty squats, five press-ups on the step, forty seconds of plank.",
   "One minute of standing about, then round two, the same.",
   "It should take about six minutes in all.",
   "Two rounds is your session from now on."],
  "Volume is the quiet ingredient. Two rounds three times a week is six times as much work as one round once, and it still costs you six minutes."),
 ("Do thirty squats in one go.",
  'skill', 'room',
  ["Thirty is where squats become breathing as much as legs. Let yourself breathe out on the way up.",
   "Keep the last five as clean as the first five.",
   "Legs shaking is normal. Knees caving inwards is not — push them out over your toes.",
   "If thirty is easy, do them with a four-second lowering instead and count that."],
  "Thirty good squats a few days a week is enough on its own to change how stairs, hills and getting off the floor feel. Most people notice that before they notice anything in the mirror."),
 ("Do two press-ups on the floor, chest all the way down.",
  'skill', 'room',
  ["Hands under your shoulders, body one straight line from heels to head.",
   "Down until your chest is a fist's width from the floor, then all the way up. Nothing half-way counts.",
   "Two is the rung. Two proper ones, not five bad ones.",
   "Cannot get one? Go back to the bottom step for another week — it will come."],
  "This is the rung people remember. The first real press-up off the floor is a moment, and almost everybody who does the rounds three times a week gets there within a few weeks of starting. If you could already do two on day one, the rung is two slow ones: three seconds down, three seconds up."),
 ("Hold a plank for one minute.",
  'skill', 'room',
  ["Timer on, hips level, breathing.",
   "Break it into thirty and thirty with a rest if you must, then try the full minute two days later.",
   "Look at the floor, not up — your neck should follow the line of your back.",
   "One honest minute is a real thing to own."],
  "A minute is the standard most people will never need to go past for ordinary life. If it is easy, lift one foot off the floor for the last fifteen seconds rather than holding for five minutes."),
 ("Do ten rows: lie under a sturdy table, grab the edge, and pull your chest up to it.",
  'skill', 'room',
  ["Heels on the floor, body straight, arms straight at the bottom.",
   "Pull until your chest touches the underside of the table edge, then lower all the way down.",
   "Too hard? Bend your knees and put your feet flat — that takes weight off.",
   "No table you trust? A bannister, a low bar in a park, or a broom handle across two chairs."],
  "Everything so far has been pushing. This is the first pulling, and it is the half of the body that a floor programme normally forgets. Do it and your shoulders will thank you; skip it and press-ups slowly round your back."),
 ("Do five press-ups on the floor without stopping.",
  'skill', 'room',
  ["Same shape. Five in a row, no resting at the top.",
   "If you get three, rest twenty seconds and do two more. Next session, go for four in a row.",
   "Add floor press-ups into your round now, even if it is only three.",
   "Chest all the way down, every time."],
  "Two to five is usually about two weeks. This is also the point where the easiest mistake appears: chasing the number and letting the depth go. Half press-ups do not build anything. Count only the ones that go all the way down."),
 ("Do forty squats in one go.",
  'skill', 'room',
  ["Pace yourself from the first one. Steady, not fast.",
   "Breathe in on the way down, out on the way up, every rep.",
   "If your heels lift near the end, that is fatigue — stop there and call it the number.",
   "Split into twenty and twenty if you must, then try the forty again in two days."],
  "Forty in one go is a genuine bit of fitness, not a beginner's number. If you are already past forty, do twenty with something heavy held at your chest — a bag of potatoes, a full rucksack, a child — and count that."),
 ("Do the round three days a week for a fortnight, without missing one.",
  'attention', 'long',
  ["Six sessions in fourteen days. Two rounds each session.",
   "Write the six days down before you start and tick them off.",
   "A session missed gets made up the next day — it does not get skipped.",
   "Anything is better than nothing: one round, half a round, five squats in the kitchen all count as turning up."],
  "This is the rung that makes the rest of your life easy. After a fortnight of not missing, the sessions stop needing a decision. If you miss one anyway, do not start the fortnight again — just do the next one."),
 ("Do ten press-ups on the floor without stopping.",
  'skill', 'room',
  ["Ten in a row, chest to the floor every time, no rest at the top.",
   "Get there by doing more sets of fewer: six, six, six is how you get to ten.",
   "Fresh, at the start of a session, not at the end of it.",
   "When you have it, do it again two days later to be sure it was not a one-off."],
  "Ten proper press-ups from a standing start of none is the end of this ladder and it is a real thing. Most people who do the rounds three times a week are here inside three months. Thirty is part two and the press-up ladder; you are now well on the way to both."),
 ("Write the three numbers again, underneath the first three.",
  'attention', 'room',
  ["Same three: press-ups in one go, squats in one go, seconds of plank.",
   "Same conditions — fresh, with a rest between each.",
   "Write them under the old ones with today's date, so you can see the two sets together.",
   "Then read the first line again."],
  "This is the whole point of rung one. Numbers you wrote before you believed anything would happen are the only proof that cannot be argued with. Keep the paper: part two starts by setting the next three."),
])

lib.put(d, 'fit.body2', cid='fit', name='Getting strong, part two', size='months',
        strand='get-strong-outside', after='fit.body1',
        line='From ten press-ups to twenty, two minutes of plank, and a body used outside the room.',
        about=("Part one built the round. Part two makes it heavier and then takes it outdoors: the same "
               "three moves going up, pulling added properly, a walk that turns into a run, and something "
               "heavy carried down the street. It ends by asking you to pick the one ladder you want to push "
               "a long way — press-ups to thirty, squats to a hundred, a first pull-up, five kilometres — "
               "because by then you will know which one you actually want."),
        rungs=[
 ("Write down the three you are going for: twenty press-ups, sixty squats, two minutes of plank.",
  'attention', 'room',
  ["Under the two sets of numbers from part one.",
   "Add the date you expect to have them. Be generous: about three months.",
   "These are the ends of this ladder, not a hope.",
   "If you are already past one of them, write the next number up instead and aim there."],
  "Named targets beat good intentions because you can tell whether you hit them. Everything in this ladder walks towards these three."),
 ("Do the round twice through on three days in one week, at part one's finishing numbers.",
  'attention', 'long',
  ["Forty squats, ten floor press-ups, one minute of plank, ten rows. Twice through.",
   "Three days, a rest day between where you can.",
   "About twelve minutes a session now.",
   "Get this week done before you chase any new number."],
  "Part one ended at these numbers once. This rung makes them your ordinary Tuesday. If that feels like a step backwards, it is not — comfortable is exactly what it is meant to become."),
 ("Do twelve press-ups in one go.",
  'skill', 'room',
  ["Fresh, at the start of the session.",
   "Chest down to a fist's width from the floor each time.",
   "Get there with sets of eight: eight, eight, eight with a minute between beats one all-out set.",
   "Twelve in a row, no resting at the top."],
  "From here on, the press-up number climbs two at a time and every climb is bought with sets you do on the days between."),
 ("Walk for forty-five minutes without stopping.",
  'skill', 'out',
  ["Out the door, one direction, twenty-two minutes, then turn round.",
   "Proper walking pace — enough that you could talk but would rather not sing.",
   "Phone in your pocket, not in your hand.",
   "Rain is fine. Rain is usually better."],
  "A long walk is the base everything else sits on, and it is the one piece of training nobody is too unfit or too tired for. If you already walk this much, do it somewhere you have never walked before and count that."),
 ("Do fifty squats in one go.",
  'skill', 'room',
  ["Steady from the first rep. This is now a breathing exercise as much as a leg one.",
   "Thighs level every time — the last ten are where depth quietly disappears.",
   "Break as twenty-five and twenty-five with ten seconds between, then close the gap over a fortnight.",
   "Shaking legs afterwards is normal and passes in a minute."],
  "Fifty in one go puts you past almost everybody you know. It is also where you stop needing a warm-up for ordinary life."),
 ("Hold a plank for ninety seconds.",
  'skill', 'room',
  ["Timer on. Hips level the whole way or it does not count.",
   "Squeeze your backside hard — that is the trick that buys the last twenty seconds.",
   "Breathe in a steady rhythm rather than gritting your teeth.",
   "If you break at seventy, hold seventy twice with a minute's rest and go again in two days."],
  "Past a minute the plank is mostly a test of whether you will stay calm while something is uncomfortable. That is worth practising on its own."),
 ("Do ten press-ups slowly — three seconds down, three seconds up.",
  'skill', 'room',
  ["Count it out loud or in your head. Three full seconds each way.",
   "That is sixty seconds of work. It is much harder than ten normal ones.",
   "If you fail at seven, that is the rung for another week.",
   "Do not let the last few speed up. Slow is the whole point."],
  "Time under strain, not the number of reps, is what actually builds the muscle. This one rung is why your normal press-up number jumps a fortnight later."),
 ("Do twenty rows under a table.",
  'skill', 'room',
  ["Body straight, chest all the way to the table edge, arms straight at the bottom.",
   "Twenty in one go. Legs straight out makes it harder, knees bent makes it easier.",
   "Rest your heels on a chair to make it harder still, once twenty is easy.",
   "Keep these in every round — pulling is half of a body."],
  "Twenty honest rows is roughly the strength that a first pull-up is built on. If you want the pull-up ladder later, this is the rung that pays for it."),
 ("Carry something heavy in each hand the length of your street, without putting it down.",
  'skill', 'out',
  ["Two full shopping bags, two water containers, a bag of coal, two full buckets.",
   "Stand tall, shoulders back, walk normally. Do not lean.",
   "If you have to stop, the load is right — pick something slightly lighter and go again.",
   "No heavy things at home? Fill two bags with books, or two containers with water from the tap."],
  "This is the strength that actually shows up in a life: shopping, moving house, carrying a child who has fallen asleep. It costs nothing and no gym machine trains it better than two heavy bags."),
 ("Do fifteen press-ups in one go.",
  'skill', 'room',
  ["Fresh, first thing in the session.",
   "Ten, then breathe at the top without dropping your hips, then five more if you must — but aim for fifteen straight.",
   "Depth over number, every single time.",
   "Do it once, then get it again two days later."],
  "Fifteen is three quarters of the way to this ladder's target and about half way to the press-up ladder's thirty."),
 ("Hang from a bar with your feet off the ground for thirty seconds.",
  'skill', 'kit',
  ["A park bar, a beam, a strong door frame bar, a low tree branch.",
   "Hands a little wider than your shoulders, arms straight, feet off the ground.",
   "Let your shoulders stretch at first, then pull them down away from your ears and hold that.",
   "Free option: almost every play park and outdoor gym in the country has a bar."],
  "A hang decompresses everything that sitting compresses, and it builds the grip that pull-ups, carrying and lifting all need. Thirty seconds is a lot the first time and easy within a fortnight."),
 ("Hold a plank for two minutes.",
  'skill', 'room',
  ["Timer, level hips, steady breathing.",
   "Pick a spot on the floor and stay with it.",
   "If the line breaks, come down — the two minutes only count if the shape holds.",
   "Once you have it, stop chasing plank time and make it harder instead: lift one foot, then the other."],
  "Two minutes is the honest end of the plank for ordinary strength. Anything past it is a party trick, and the side plank and the one-foot version buy you far more."),
 ("Do sixty squats in one go.",
  'skill', 'room',
  ["Pace it like a run, not a sprint. The first thirty should feel too easy.",
   "Breathe every rep. Holding your breath is what makes fifty feel like a hundred.",
   "Depth to the last one.",
   "Too easy? Hold something heavy at your chest and do thirty instead."],
  "That is one of your three targets reached. Write it down next to the date you guessed at the start."),
 ("Do the round three days a week for a fortnight, without missing one.",
  'attention', 'long',
  ["Six sessions in fourteen days, at your current numbers, two rounds each.",
   "Write the six dates down first, tick them off.",
   "Missed one? Do it the next day. Do not restart the fortnight.",
   "Short and done beats long and skipped."],
  "This is the same rung as part one's, and it is here again on purpose: consistency is not a thing you learn once. Two clean fortnights is what makes the rest of this a habit instead of a project."),
 ("Do ten press-ups with your feet up on a chair.",
  'skill', 'room',
  ["Feet on a chair or the second step, hands on the floor, body in one straight line.",
   "More of your weight goes through your arms, so ten here is worth about fifteen flat.",
   "Chest all the way to the floor, as always.",
   "Higher feet, harder press-up — that is the dial from now on."],
  "Now that the floor is comfortable, this is how you keep getting stronger without ever needing weights. Feet up is the same move with the dial turned."),
 ("Run for five minutes without stopping.",
  'skill', 'out',
  ["Slow. Slower than you think — a pace you could hold a conversation at.",
   "Five minutes, clock running, no walking breaks.",
   "Any shoes that do not hurt. Any road, path or field.",
   "Already a runner? Run five minutes at a pace that makes talking impossible instead."],
  "Almost everybody can run for five minutes if they go slowly enough, and almost everybody tries to go too fast and finds out they cannot. Slow it right down and it is yours today."),
 ("Do twenty press-ups in one go.",
  'skill', 'room',
  ["Fresh, first thing, chest all the way down.",
   "Build it with sets of twelve to fifteen on the days between.",
   "Twenty in a row, no rest at the top.",
   "Get it twice in one week before you call it yours."],
  "That is the second of your three targets. Twenty proper press-ups is more than most adults will ever do in one go, and it came from a windowsill."),
 ("Lower yourself slowly from the top of a pull-up, three times.",
  'skill', 'kit',
  ["Jump or step up so your chin is over the bar, then lower yourself as slowly as you can.",
   "Five seconds is good, ten is excellent. Stay in control all the way to straight arms.",
   "Rest a full minute between each one. Three is plenty.",
   "Step off a bench or a low wall to get to the top if you cannot jump there."],
  "You can lower far more than you can lift, which is why this is how a first pull-up is built. Three of these twice a week is the whole secret, and it is where the pull-up ladder begins."),
 ("Do something physical with somebody else, twice in one week.",
  'kindness', 'with',
  ["A walk, a swim, a kickabout, a bike ride, a climb up a hill, a game in the garden.",
   "It does not have to be hard. It has to be with somebody.",
   "Ask — most people say yes and nobody ever asks them.",
   "Free option: a walk costs nothing and is the easiest thing in the world to say yes to."],
  "Training on your own works until the week it does not. Somebody expecting you is the strongest thing there is for keeping this going, and it turns exercise into time with people, which is a better deal than it sounds."),
 ("Write your three numbers again, and pick the one ladder you want to push a long way.",
  'attention', 'room',
  ["Press-ups, squats, plank — under the two earlier sets.",
   "Then read the Fitness path and pick one: press-ups to thirty, squats to a hundred, a first pull-up, five kilometres, a hundred metres flat out.",
   "One, not four. The point is to take one thing a long way.",
   "Keep doing the round while you climb it — the round is now your base, not your project."],
  "Two programmes, three sets of numbers, and a body that can do things it could not do at the start. From here the single-move ladders go much further than these rounds ever will, and you now know which of them you actually want."),
])

lib.save(d)
lib.report(d, ['fit.body1', 'fit.body2'])
