# -*- coding: utf-8 -*-
"""Stretching, running, sprinting, swimming. The lines now match the last rung
   (stretching said 'to the splits' and ended at palms flat; pull-ups said ten
   and ended at four), and the stretching order was shuffled into the order you
   would actually take it."""
import lib
d = lib.load()

lib.put(d, 'fit.stretch', name='Bending and stretching', size='months',
        line='From reaching past your knees to both palms flat on the floor.',
        about=("Getting back the range you had as a child. Palms flat on the floor with straight legs is a "
               "genuinely hard thing that most adults cannot do, and it takes five or ten minutes a day for a "
               "few months rather than any talent. It needs no equipment, no space and no money, and unlike "
               "almost everything else physical, it is easiest to do at the end of the day in front of the "
               "fire. Everything else in the Fitness path works better once you have it."),
        rungs=[
 ("Stand with straight legs and reach past your knees.",
  'skill', 'room',
  ["Feet together, knees locked but not jammed back.",
   "Fold from the hips rather than curling your shoulders down.",
   "Wherever your hands get to, stop and breathe there for twenty seconds."],
  "This is a measurement, not a competition. Wherever you reach today is the honest start, and it moves faster than anything else in this school."),
 ("Sit on the floor with your legs straight out and reach towards your ankles.",
  'skill', 'room',
  ["Sit up tall first, then hinge forward from the hips.",
   "Knees pressed down, toes pointing up.",
   "Sitting on the edge of a cushion makes it much easier at the start."],
  "Sitting takes your balance out of the equation so you feel the stretch where it actually is: the backs of your legs."),
 ("Hold a hamstring stretch for a full minute on each leg.",
  'skill', 'room',
  ["Lie on your back, one leg straight up, hands behind the thigh, other leg flat on the floor.",
   "Straight knee on the lifted leg matters more than how high it goes.",
   "Breathe out and let it sink a little further every few breaths."],
  "A minute is where a stretch stops being a stretch and starts being a change. Thirty seconds feels nice and does much less."),
 ("Stretch for five minutes every morning for five days running.",
  'attention', 'long',
  ["Same five minutes: standing fold, sitting fold, one minute a leg on your back.",
   "Set it right after something you already do — the kettle, the shower.",
   "Five days, ticked off."],
  "Stretching answers to how often more than any other kind of training. Five minutes daily beats an hour on a Sunday by a distance."),
 ("Touch your toes with your knees slightly bent.",
  'skill', 'room',
  ["Soft knees, fold from the hips, let your head hang heavy.",
   "Hold for thirty seconds rather than bouncing at it.",
   "Bend as much as you need to reach — this rung is about the fold, not the legs."],
  "Bent knees take the backs of your legs out of it and let your lower back open. It is the honest halfway house to the real thing."),
 ("Hold a deep squat with your heels down for thirty seconds.",
  'skill', 'room',
  ["All the way down, heels flat, backside near your ankles.",
   "Hold a door frame at first if you fall backwards.",
   "Heels lifting? Stand them on a folded towel and lower it over the weeks."],
  "This is the position half the world still rests in. Getting it back opens your ankles and hips, which is most of what stops people touching their toes."),
 ("Reach one hand over your shoulder and the other up your back, and touch your fingers.",
  'skill', 'room',
  ["One arm up and over, elbow pointing at the ceiling; the other arm up behind your back.",
   "Walk the fingers towards each other.",
   "Hold a tea towel between your hands and climb it if they do not meet."],
  "Shoulders quietly close up from years of desks and phones. The tea towel is how you measure the gap closing week by week."),
 ("Do the same with the other arm on top.",
  'skill', 'room',
  ["Swap which arm goes over the shoulder.",
   "One side will be clearly worse. That side gets twice the practice.",
   "Tea towel again if needed."],
  "Everybody is lopsided here and almost nobody notices until they try it. Evening the two sides up is worth more than making the good side better."),
 ("Hold the deep squat for a full minute.",
  'skill', 'room',
  ["Nothing to hold on to, heels flat, back reasonably straight.",
   "Move about, look around, breathe — it is a rest, not a hold.",
   "Two thirties with a rest is fine on the way there."],
  "A minute at the bottom with nothing to hold means your ankles and hips have genuinely opened. Everything below gets easier from here."),
 ("Stretch every day for two weeks without missing one.",
  'attention', 'long',
  ["Ten minutes: the folds, a minute a leg, a deep squat, both shoulders.",
   "Fourteen days in a row, written down and ticked off.",
   "Miss one and do it that evening rather than restarting."],
  "This fortnight is where the change becomes yours rather than borrowed. Range you stop using goes away again within a month, which is the whole reason for the habit."),
 ("Touch your toes with your legs completely straight.",
  'skill', 'room',
  ["Feet together, knees locked, fold from the hips.",
   "Come up slowly rather than snapping up.",
   "Warm first — after a walk or a bath is far easier than cold."],
  "This is the one everybody has heard of, and most adults cannot do it. If you have it already, hold your toes for thirty seconds and move on."),
 ("Hold your toes for thirty seconds with your legs straight.",
  'skill', 'room',
  ["Get down there, take hold, and stay.",
   "Breathe out and let it sink on each breath.",
   "Straight knees the whole time or it is a different exercise."],
  "Touching and holding are two different things. Holding is what actually moves the range."),
 ("Sit with your legs wide and lean forward until your elbows reach the floor.",
  'skill', 'room',
  ["Legs as wide as is comfortable, toes up, sit tall first.",
   "Hinge from the hips, not from your back.",
   "Sit on a cushion to tip your hips forward if you cannot sit up straight."],
  "The insides of the legs are the piece that the toe-touch never reaches and the piece that makes sitting on the floor comfortable again."),
 ("Lie on your back and pull one straight leg up until it points at the ceiling.",
  'skill', 'room',
  ["Other leg flat on the floor, both knees straight.",
   "Hands behind the thigh or a towel round the foot to pull gently.",
   "Hold a minute each side."],
  "Straight up with the other leg flat is a proper hamstring, and having it on both sides is what makes running and lifting safe."),
 ("Kneel, lean back and hold your heels for twenty seconds.",
  'skill', 'room',
  ["Kneel with your feet behind you, hips pushed forward, reach back for your heels.",
   "Hips forward is the rung — do not just fold backwards from the waist.",
   "Hands on a low chair behind you instead, if the heels are too far."],
  "This opens the fronts of your hips and thighs, which shorten from sitting more than any other part of you."),
 ("Hold a lunge stretch for a minute on each side.",
  'skill', 'room',
  ["One foot forward, back knee on the floor, hips pushed forward and down.",
   "Chest up and back straight — do not lean over the front leg.",
   "A folded towel under the back knee makes it bearable."],
  "The front of the hip is the quiet cause of most sore lower backs. A minute a side, daily, is a remarkably good trade."),
 ("Put your knuckles on the floor with your legs straight.",
  'skill', 'room',
  ["Fold from the hips, straight knees, reach for the floor with loose fists.",
   "Warm up first. Cold, this rung will not come.",
   "Hold for twenty seconds once you get there."],
  "Knuckles down is the last stop before palms, and the point at which strangers start commenting on it."),
 ("Hold a bridge — hands and feet down, hips up — for twenty seconds.",
  'skill', 'room',
  ["Lie on your back, hands by your ears, push up onto your hands and feet.",
   "Hips as high as they go, arms pushing you away from the floor.",
   "Too hard? Push up onto the top of your head first, then to straight arms over a few weeks."],
  "The bridge is everything this ladder has opened, all at once: shoulders, hips and back. It is also the most fun thing here."),
 ("Put both palms flat on the floor with your knees a little bent.",
  'skill', 'room',
  ["Small bend in the knees, fold from the hips, both palms flat.",
   "Then try straightening the knees a fraction at a time.",
   "Warm, at the end of the day, is when this will come."],
  "Palms flat with soft knees means you already have the range. The last rung is simply the same thing with the knees locked."),
 ("Put both palms flat on the floor with your legs straight, and hold it for ten seconds.",
  'skill', 'room',
  ["Feet together, knees locked, both palms flat, ten seconds.",
   "Come up slowly.",
   "Do it again two days later to be sure it was not a warm-day fluke."],
  "That is the ladder. Most adults cannot do this, most assume it is a thing you are born with, and it took you ten minutes a day and no money at all."),
])

lib.put(d, 'body.run', name='Running', size='months', line='From one minute without stopping to five kilometres.',
        about=("Running from nothing to five kilometres, the way it actually works: slowly. Almost everybody "
               "who says they cannot run is simply running too fast, and the whole first half of this ladder "
               "is about going slow enough to keep going. It needs shoes that do not hurt and a road. Three "
               "times a week for about three months takes most people from a minute to five kilometres "
               "without stopping."),
        rungs=[
 ("Run for one minute without stopping.",
  'skill', 'out',
  ["Slower than you think — a pace you could hold a conversation at.",
   "One minute on the clock, then walk.",
   "Any shoes that do not hurt. Any pavement, path or field."],
  "If one minute is hard, you are going too fast, not too unfit. Halve the speed and try again — it works every time."),
 ("Run one minute and walk one minute, eight times over.",
  'skill', 'out',
  ["Sixteen minutes in all. Clock or phone timer running.",
   "The running minutes stay slow; the walking minutes are proper walking, not shuffling.",
   "Finish feeling like you could have done another."],
  "Run-walk is not a beginner's compromise, it is how nearly every runner is actually built. Do not skip it because it feels too easy."),
 ("Run for three minutes without stopping.",
  'skill', 'out',
  ["Same slow pace. Breathing through your nose is a good check.",
   "Three minutes, then walk as long as you like.",
   "Two or three of these in one outing is a good session."],
  "Three minutes usually arrives within a week of the run-walks. Nothing has got fitter yet — you have just stopped sprinting."),
 ("Go running three times in one week.",
  'attention', 'long',
  ["Three outings, twenty minutes each, mostly walking at first if you need it.",
   "A day off between where you can.",
   "Write the three days down and tick them off."],
  "Three a week is the whole thing. Everything from here is built on it, and one long run on a Sunday builds far less than three short ones."),
 ("Run for five minutes without stopping.",
  'skill', 'out',
  ["Still slow. If you cannot talk, slow down.",
   "Five minutes, walk five, five more.",
   "Rain is fine. Rain is usually better."],
  "Almost everybody can run for five minutes if they go slowly enough, and almost everybody tries to go too fast and learns they cannot."),
 ("Run for eight minutes without stopping.",
  'skill', 'out',
  ["Pick a route you know so you are not guessing the distance.",
   "Steady. Boring is the correct feeling.",
   "Walk as much as you like afterwards."],
  "Eight minutes is where the legs stop being the limit and breathing takes over. Steady breathing in a rhythm is what carries you from here."),
 ("Run for ten minutes without stopping.",
  'skill', 'out',
  ["Out for five, turn round, back for five.",
   "Same slow pace the whole way, including the last minute.",
   "Get it twice before you move on."],
  "Ten minutes without stopping is roughly a mile for most beginners, which means the next rung is already nearly yours."),
 ("Run a mile without walking any of it.",
  'skill', 'out',
  ["Measure it on a phone map, or use a known lap.",
   "Start slower than you want to. Almost everybody goes out too fast.",
   "Finish it, however slowly."],
  "A mile is the first real milestone and the first one worth telling somebody about. It is also a distance you now have for good."),
 ("Go out and run in the rain on purpose, and finish.",
  'courage', 'out',
  ["Wait for the rain, put your shoes on, go.",
   "You will be wet in the first two minutes and then it stops mattering.",
   "Dry clothes and something warm waiting for you at home."],
  "This is the rung that makes you a person who runs, because the weather stops being a decision. It is also more enjoyable than anybody expects."),
 ("Run for fifteen minutes without stopping.",
  'skill', 'out',
  ["Pace it so the last three minutes are the same speed as the first three.",
   "Steady breathing, easy shoulders, short steps.",
   "Walk home afterwards rather than stopping dead."],
  "Fifteen minutes is where a run becomes a thing you can think during. That is when people start looking forward to it."),
 ("Run three times a week for a fortnight.",
  'attention', 'long',
  ["Six runs in fourteen days. Two short, one longer, each week.",
   "Write the six down first and tick them off.",
   "Miss one? Do it the next day. Do not restart the fortnight."],
  "This fortnight is the whole difference between someone who has been for a run and someone who runs. Nothing else on this ladder matters as much."),
 ("Run for twenty minutes without stopping.",
  'skill', 'out',
  ["Out ten, back ten, at a pace you could talk at.",
   "Take a drink of water beforehand rather than carrying one.",
   "Slow down rather than stopping if it gets hard."],
  "Twenty minutes is about two miles for most people and it is the point where fitness starts to show up in the rest of your day."),
 ("Run two miles without walking.",
  'skill', 'out',
  ["Measure the route, run it, no walking breaks.",
   "Start slow enough that the second mile is the same speed as the first.",
   "It should take twenty to twenty-five minutes."],
  "Doubling the mile is mostly patience rather than fitness. Go out slower than feels right and it does itself."),
 ("Run up a hill without walking any of it.",
  'skill', 'out',
  ["Short steps, lean in slightly, arms working.",
   "Slow right down — the rung is not stopping, not going fast.",
   "No hill nearby? A long steady road bridge, or twenty flights of stairs."],
  "Hills are where the actual fitness gets built, and where a slow pace is not embarrassing but correct. One hill a week is plenty."),
 ("Run for twenty-five minutes without stopping.",
  'skill', 'out',
  ["A new route is easier than a known one at this length.",
   "Take the first five minutes far slower than the rest.",
   "Eat something small an hour or two before."],
  "Past twenty minutes the run becomes the easy part of the day rather than the hard part. Most people find this stretch the most enjoyable."),
 ("Run for thirty minutes without stopping.",
  'skill', 'out',
  ["Fifteen out, fifteen back, steady the whole way.",
   "Walk for five minutes first as a warm-up.",
   "Water afterwards, and something to eat."],
  "Half an hour of continuous running is a properly fit adult by any ordinary standard, and it is about three kilometres to four for most people."),
 ("Run four kilometres without stopping.",
  'skill', 'out',
  ["Measure the route rather than guessing it.",
   "Even pace, no heroics in the first kilometre.",
   "Finish with something left."],
  "Four is the last rung before the one everybody has heard of, and by now the distance is a pacing job rather than a fitness one."),
 ("Run five kilometres without stopping.",
  'skill', 'out',
  ["Measured route, or a parkrun on a Saturday morning, which is free everywhere.",
   "Start at your talking pace and stay there until the last kilometre.",
   "Whatever the time is, the rung is finishing without walking."],
  "Five kilometres from a start of one minute, in about three months, with no money spent on anything but shoes. This is the rung the whole ladder was built for."),
 ("Run five kilometres faster than the first time you did it.",
  'skill', 'out',
  ["Same route, timed, at least a fortnight later.",
   "Hold back for the first two kilometres and spend it in the last one.",
   "Any improvement counts, by a second or by five minutes."],
  "Beating your own old number is a cleaner satisfaction than beating anybody else's, and it is available to you for the rest of your life."),
 ("Run beside somebody doing their first mile, and finish at their pace.",
  'kindness', 'out',
  ["Their pace, not yours, the whole way. Talk to them.",
   "Tell them the run-walk method and that going slowly is the trick.",
   "Finish together and make a proper fuss of it."],
  "Running somebody else's first mile with them costs you an easy twenty minutes and gives them the thing you have. It is the best use of this ladder there is."),
])

lib.put(d, 'fit.sprint', name='Sprinting', size='weeks', line='From ten seconds flat out to a hundred metres you have beaten twice.',
        about=("Flat-out running is a different quality from distance running, it is the first one to go with "
               "age, and it is almost never practised after school. This ladder is short on purpose: a handful "
               "of sprints with long rests, once or twice a week, on grass if you can. It costs nothing and it "
               "makes you feel about fifteen."),
        rungs=[
 ("Sprint flat out for ten seconds.",
  'skill', 'out',
  ["Warm up first: five minutes of walking and jogging, then a few faster runs.",
   "Ten seconds at about nine tenths, not a hundred per cent, the first time.",
   "Grass or a track is kinder than pavement."],
  "Never sprint cold. Pulled hamstrings almost always happen on the first sprint of the day, and five minutes of warming up prevents nearly all of them."),
 ("Sprint ten seconds, walk a minute, and do it five times.",
  'skill', 'out',
  ["Five sprints, full walking recovery between each.",
   "If the fifth is much slower than the first, your rests are too short.",
   "The whole session is about eight minutes plus the warm-up."],
  "Long rests feel like cheating and are the entire method. Sprinting trains speed, and speed is only trained when you are fresh."),
 ("Run a hundred metres without slowing down at the end.",
  'skill', 'out',
  ["Pace out a hundred metres, or use a football pitch — it is about one and a bit lengths.",
   "Build up over the first twenty metres rather than exploding off the line.",
   "Run through the finish, not to it."],
  "Nearly everybody slows in the last twenty metres. Holding the speed to the line is the skill and it is worth more than a fast start."),
 ("Time your hundred metres and write the number down.",
  'attention', 'out',
  ["Get somebody to time you, or use a phone stopwatch on a wall.",
   "Warm up properly, then one honest run.",
   "Write it down with the date, whatever it is."],
  "Whatever the number, it is your number and it is about to get smaller. Nobody else ever sees it."),
 ("Sprint from a standing start ten times, resting properly between each.",
  'skill', 'out',
  ["Thirty to forty metres each, walk back slowly, go again when your breath is back.",
   "Two full minutes between sprints is not too long.",
   "Stop the session the moment they start getting slower."],
  "The standing start is where the power is. Stopping while you are still fast is how you get faster, which is the opposite of how most training feels."),
 ("Sprint uphill five times.",
  'skill', 'out',
  ["A short steep hill, twenty or thirty metres, walk down between each.",
   "Drive the arms, short steps, lean into the hill.",
   "No hill? A steep set of steps or a long ramp."],
  "Hill sprints are the safest kind — the hill slows you down just enough that hamstrings almost never complain — and they build power quickly."),
 ("Beat your hundred metre time.",
  'skill', 'out',
  ["Same stretch of ground, same timing method, a fresh day.",
   "Warm up longer than last time. It is worth a tenth of a second on its own.",
   "Write the new number under the old one."],
  "The first improvement is usually large and is mostly technique: warming up, building speed properly, and running through the line."),
 ("Sprint on two separate days in one week.",
  'attention', 'long',
  ["Two sessions, five or six sprints each, long rests.",
   "Never on back-to-back days — this needs the recovery.",
   "Write the two days down and tick them off."],
  "Twice a week is the most sprinting anybody needs. Any more and the sessions get slower, which trains the opposite of what you want."),
 ("Run a hundred metres in under twenty seconds.",
  'skill', 'out',
  ["Full warm-up, one honest run, timed.",
   "Relaxed face and shoulders — tension is slow.",
   "Run through the line."],
  "Twenty seconds is a comfortable jog for a sprinter and a real effort for most adults. It is the first proper marker on the way down."),
 ("Run a hundred metres in under eighteen seconds.",
  'skill', 'out',
  ["Warm up thoroughly, then two attempts at most, with a long rest between.",
   "Drive the first twenty metres, then relax and hold it.",
   "Grass costs you a second or so against a proper track — do not let that put you off."],
  "This is where your hill sprints and standing starts show up. From here the improvements get smaller and harder, which is fine."),
 ("Run a hundred metres in under sixteen seconds.",
  'skill', 'out',
  ["Only on a day you are fresh and properly warm.",
   "One good run beats four tired ones.",
   "Have somebody time you rather than doing it yourself."],
  "Under sixteen is a genuinely quick hundred metres for an adult who is not training for it. That is the number end of this ladder."),
 ("Race somebody, and beat your own old time doing it.",
  'courage', 'out',
  ["Anybody — a friend, a brother, one of the children with a head start.",
   "Time the race as well as running it.",
   "The rung is your own old number, not theirs."],
  "Racing somebody makes you faster than any session will, because you forget to hold anything back. It is also the most fun this ladder gets."),
])

lib.put(d, 'water.swim', name='Swimming', size='months', place='pool',
        line='From your face in the water to fifty metres without stopping.',
        about=("Swimming is the one thing on this list that is a safety skill as well as a fitness one, and "
               "the water is patient: it takes almost everybody from blowing bubbles to fifty metres inside a "
               "few months. It needs a pool, which is the only cost here — most council leisure centres are a "
               "few pounds and many have free or cheap family sessions. Nothing else in the school trains "
               "your breathing and your whole body at once like this."),
        rungs=[
 ("Put your face in the water and blow bubbles, ten times.",
  'skill', 'out',
  ["Shallow end, hold the side, take a breath, face in, blow out slowly through your nose and mouth.",
   "Ten times, each one a little longer.",
   "Breathing out under the water is the whole foundation. Nobody swims well while holding their breath."],
  "This is the rung that adults skip and then wonder why swimming feels like a panic. Blowing out under water is what makes everything above it calm."),
 ("Hold the side and kick your legs for thirty seconds.",
  'skill', 'out',
  ["Arms straight, holding the rail or the edge, body flat on the surface.",
   "Kick from the hips with straight-ish legs and loose ankles, small and fast.",
   "Small splashes, not big ones — big splashes mean the knees are doing it."],
  "The kick does less than people think for moving you and a lot for keeping you flat. Flat is what makes swimming easy."),
 ("Push off the side and glide with your face in, as far as you can.",
  'skill', 'out',
  ["Feet on the wall, arms stretched out in front, head between your arms, face down.",
   "Push off and go — no kicking, no pulling. Just hold the shape.",
   "See how far the glide takes you before you need to stand up."],
  "A good glide is the whole of good swimming. Everything you learn from here is about keeping that shape while you add the arms and legs."),
 ("Float on your front for five seconds, then stand back up.",
  'skill', 'out',
  ["Face in, arms out, let your legs come up behind you.",
   "Relax — tension sinks and calm floats.",
   "To stand: tuck your knees to your chest, put your feet down, lift your head last."],
  "Being able to stop and stand up calmly is what takes the fear out of the deep bit. Practise the standing-up as much as the floating."),
 ("Float on your back for ten seconds.",
  'skill', 'out',
  ["Head back so your ears are in the water, hips up, arms out to the sides.",
   "Look straight up at the ceiling. Looking at your feet sinks you.",
   "Somebody's hand under your back at first if it helps."],
  "Floating on your back is the single most useful thing in the water: it is how anybody in trouble rests. Worth having for its own sake."),
 ("Push off and glide with a leg kick, three metres.",
  'skill', 'out',
  ["Same glide shape, then add the small fast kick you practised at the side.",
   "Face down, breathing out slowly the whole way.",
   "Three metres, then stand up calmly."],
  "Glide plus kick is already swimming — you simply have no arms in it yet. Getting this bit right makes the arms easy."),
 ("Swim five metres any way you like, without touching the bottom.",
  'skill', 'out',
  ["Doggy paddle, breaststroke, anything. Five metres, feet off the bottom.",
   "Along the shallow end, so you can stand whenever you want.",
   "Calm and slow beats fast and thrashing."],
  "Any five metres is a proper milestone: you are now swimming, and everything after this is refinement."),
 ("Swim ten metres on your front.",
  'skill', 'out',
  ["Face in, breathing out under water, lifting your head only when you must.",
   "Long slow arms rather than fast short ones.",
   "Ten metres is usually about half a short pool."],
  "The temptation is to lift your head and rush. Long and slow gets you further with half the effort — that is true for the whole of swimming."),
 ("Swim ten metres on your back.",
  'skill', 'out',
  ["Ears in the water, hips up, small kick, arms brushing past your ears one at a time.",
   "Look straight up. Glance at the wall behind you as you approach it.",
   "On your back you can always breathe, which is why it is the restful one."],
  "Front and back both means you always have a way to keep going when one of them tires. It also means you can rest without touching the bottom."),
 ("Turn your head to the side, take one breath, and keep swimming.",
  'skill', 'out',
  ["Breathe out under the water first, then turn your head — do not lift it.",
   "One ear stays in the water as you breathe. The head turns, the body stays flat.",
   "Take one breath, put your face back, keep going."],
  "This one movement is the difference between swimming ten metres and swimming as far as you like. Practise it at the side of the pool before you swim with it."),
 ("Swim ten metres taking a breath every three or four strokes.",
  'skill', 'out',
  ["Steady rhythm: stroke, stroke, breathe, stroke, stroke, breathe.",
   "Breathing out continuously between breaths, never holding.",
   "Slow the arms down until the rhythm works."],
  "Once the breathing has a rhythm, distance stops being a fitness question. Most people double their distance the week this clicks."),
 ("Jump in from the side and swim back to it.",
  'courage', 'out',
  ["Water you know the depth of, with somebody watching.",
   "Jump feet first, let yourself come back up, turn and swim to the side.",
   "Do it a second time straight away — the second is far easier."],
  "Going under and coming back up without panic is the safety skill hiding inside swimming, and it is worth practising deliberately rather than by accident."),
 ("Swim fifteen metres without stopping.",
  'skill', 'out',
  ["Long strokes, steady breathing, face in.",
   "Count your strokes — fewer strokes for the same distance means better shape.",
   "Stop calmly at the end rather than lunging for the side."],
  "Counting strokes is the swimmer's trick for improving without going faster. Fewer strokes, same distance, is always progress."),
 ("Pick something up off the bottom in water up to your chest.",
  'skill', 'out',
  ["A diving toy, a coin, anything that sinks.",
   "Breathe out as you go down, eyes open, take it, push off the bottom.",
   "Three or four goes. It gets easy quickly."],
  "Going down on purpose and coming back up teaches your body that under the water is a place you can visit, which takes a surprising amount of fear away."),
 ("Tread water for thirty seconds.",
  'skill', 'out',
  ["Out of your depth, or deep enough that you cannot stand.",
   "Slow circles with your hands, gentle cycling with your legs. Calm and small.",
   "Somebody watching, and the side within reach."],
  "Treading water is almost entirely about relaxing. Everybody's first attempt is far too frantic and the second one is easy."),
 ("Tread water for a full minute.",
  'skill', 'out',
  ["Same slow small movements, breathing normally.",
   "Lie back into a float for a few seconds if you need a rest, then carry on.",
   "Time it rather than guessing."],
  "A minute of treading water plus a back float means you could look after yourself in deep water long enough for help to reach you."),
 ("Swim twenty-five metres on your front without stopping.",
  'skill', 'out',
  ["A full length of most pools. Steady breathing rhythm all the way.",
   "Start slower than you want to — the second half is where people stop.",
   "Finish calmly and hold the side for a moment before standing."],
  "A full length is the milestone everybody recognises and the point at which you can call yourself a swimmer without qualifying it."),
 ("Swim twenty-five metres on your back without stopping.",
  'skill', 'out',
  ["Ears in, hips up, long arms past your ears.",
   "Count strokes so you know when the wall is coming.",
   "Straight line — one arm usually pulls harder and drifts you across."],
  "Having a second full length in a different stroke means you can now rest by changing stroke rather than by stopping."),
 ("Swim there and back with one rest in the middle.",
  'skill', 'out',
  ["Twenty-five metres, a short rest at the wall, twenty-five back.",
   "Same steady rhythm both ways.",
   "Breathe properly before you push off for the second length."],
  "This is the rung that turns one length into two, and two into as many as you like. The rest at the wall is a technique, not a weakness."),
 ("Swim fifty metres without stopping, and climb out unaided.",
  'skill', 'out',
  ["Two lengths, no touching the bottom, no holding the wall at the turn.",
   "Steady from the first stroke. Slow is what finishes it.",
   "Then out at the side on your arms, not up the steps."],
  "Fifty metres unbroken from a start of blowing bubbles, in about three months. From here, open water and the cold water ladder are both open to you."),
])

lib.save(d)
lib.report(d, ['fit.stretch','body.run','fit.sprint','water.swim'])
