# -*- coding: utf-8 -*-
"""Sit-ups, pull-ups, and the lifting/carrying split.
   body.strength was a copy of press-ups, pull-ups, plank and lifting with a few
   carries in it. It is now Carrying — moving a load over ground — and fit.lift is
   Lifting — getting a load off the floor and up high. No rung appears twice."""
import lib
d = lib.load()

lib.put(d, 'fit.situp', name='Sit-ups', size='months', line='From five to fifty, and straight legs to the ceiling.',
        about=("The front of your middle, trained on a floor with nothing else. This one stops at fifty in one "
               "go and turns to harder movements instead of bigger numbers, because a hundred fast sit-ups "
               "teaches your neck more than your stomach. Do it alongside the plank, not instead of it: one is "
               "moving, one is holding, and a middle needs both."),
        rungs=[
 ("Do five sit-ups, all the way up and all the way down.",
  'skill', 'room',
  ["Knees bent, feet flat, hands on your chest rather than behind your head.",
   "Up until your chest is near your knees, down until your shoulders touch.",
   "Feet lifting? Tuck them under a sofa while you build the strength."],
  "Hands behind the head is how people end up pulling on their own neck. Crossed on the chest from day one saves you that."),
 ("Do ten without stopping.",
  'skill', 'room',
  ["Steady, no bouncing off the floor at the bottom.",
   "Breathe out on the way up.",
   "All the way down every rep — half sit-ups are where the cheating starts."],
  "If you are already well past ten, start at the rung that is actually hard and count the ones below as done."),
 ("Hold yourself halfway up for twenty seconds.",
  'skill', 'room',
  ["Sit up halfway, lean back until you feel it, and stop there.",
   "Arms out in front, back rounded slightly, breathing.",
   "Shaking is normal. Falling back is the end of the hold."],
  "This is the position every sit-up passes through. Holding it teaches your middle to do the work that momentum was doing."),
 ("Do fifteen without stopping.",
  'skill', 'room',
  ["Same shape, same depth.",
   "Slow the last five down rather than speeding them up.",
   "Neck relaxed — if it aches, you are pulling with it."],
  "Fifteen is where sit-ups stop being about learning the movement and start being training."),
 ("Do sit-ups on three separate days in one week.",
  'attention', 'long',
  ["Three sets each day, a day off between where you can.",
   "Stop two or three short of failure every set.",
   "Write the three days down and tick them off."],
  "As with everything physical, how often beats how hard. Three short sessions a week moves the number; one long one on a Sunday does not."),
 ("Do twenty without stopping.",
  'skill', 'room',
  ["Build with sets of twelve to fifteen on your training days.",
   "Fresh, at the start of a session.",
   "Full range to the last one."],
  "Twenty is more than most people manage properly, and it is about the point where you feel it in how you get out of bed."),
 ("Do ten slowly — three seconds up and three seconds down.",
  'skill', 'room',
  ["Count it out. Sixty seconds of unbroken work.",
   "No rest at the bottom and no flopping down.",
   "Six honest slow ones beat ten rushed ones."],
  "Slow is where the strength is. This rung is why your ordinary number jumps a fortnight later without you chasing it."),
 ("Lie on your back and lift both straight legs up to vertical, ten times.",
  'skill', 'room',
  ["Hands under your backside, legs straight, lift until your feet point at the ceiling.",
   "Lower slowly. Do not let your lower back arch off the floor — if it does, bend your knees a little.",
   "Ten controlled ones."],
  "This is the lower half of your middle, which sit-ups barely touch and which is the half that protects your back."),
 ("Do thirty without stopping.",
  'skill', 'room',
  ["Find a rhythm and hold it. Count in tens.",
   "Breathe out up, in down, every rep.",
   "Shoulders to the floor at the bottom."],
  "Thirty takes about a minute. The second half is a test of staying steady rather than a test of strength."),
 ("Hold yourself halfway up for a full minute.",
  'skill', 'room',
  ["Timer on. Arms out in front, leaning back, breathing.",
   "Break it into two thirties if you must, then close the gap.",
   "Stop the second your back arches or your feet lift."],
  "A minute here is a stronger middle than forty fast sit-ups, and it is kinder to your neck and your back."),
 ("Do forty without stopping.",
  'skill', 'room',
  ["Pace it from the first rep, not the twentieth.",
   "Full range or it does not count.",
   "If you stop at thirty-four, that is the number — go again in three days."],
  "Forty is roughly the end of what more reps can teach you. From here the ladder turns to harder movements instead."),
 ("Lift both straight legs to vertical twenty times.",
  'skill', 'room',
  ["Slower on the way down than on the way up.",
   "Lower back stays flat on the floor the whole way.",
   "Hands under your backside for support if you need them."],
  "Twenty of these is a genuinely strong lower middle, and it is what stops a long day of lifting turning into a sore back."),
 ("Do a hundred across one day, in as many sets as you like.",
  'skill', 'long',
  ["Twenty every time you pass the living room floor.",
   "Nothing has to be hard. Spread them wide.",
   "Count as you go."],
  "Volume across a day builds without leaving you sore. This is the week before you go for fifty."),
 ("Hold a hollow position for thirty seconds: legs and shoulders both off the floor.",
  'skill', 'room',
  ["On your back, lower back pressed flat, legs straight out just off the floor, shoulders and arms lifted.",
   "Lower back flat is the whole exercise. The moment it arches, bring your legs higher.",
   "Knees bent makes it easier while you learn it."],
  "Gymnasts build everything on this one position. Thirty seconds of it is worth more than a hundred sit-ups and takes half a minute."),
 ("Do fifty sit-ups without stopping.",
  'skill', 'room',
  ["Fresh, first thing, at a rhythm you could keep up for eighty.",
   "Full range to the very last one.",
   "Neck loose, hands on your chest, breathing out on the way up."],
  "Fifty unbroken is the number end of this ladder. Everything after it is about making the movement harder rather than doing more of it."),
 ("Do twenty sit-ups holding something heavy on your chest.",
  'skill', 'kit',
  ["A full rucksack, a bag of rice, a heavy book held against your chest.",
   "Same shape, same range, slower.",
   "Nothing to hand? Fill a bag with books."],
  "Adding weight is how you keep this useful once fifty is easy, and it is a far better use of five minutes than a hundred fast ones."),
 ("Hold a hollow position for a full minute.",
  'skill', 'room',
  ["Timer on, lower back flat, breathing normally.",
   "Lower your legs a little each week as it gets easier — lower is harder.",
   "Break the line and the hold is over."],
  "A minute of hollow with your legs low is a very strong middle, and unlike a long plank it carries straight over into everything else."),
 ("Hang from a bar and lift your knees to your chest ten times.",
  'skill', 'kit',
  ["A park bar, a beam, a door frame bar. Hang with straight arms, feet off the ground.",
   "Knees up to your chest, then lower slowly. No swinging.",
   "Free option: almost every play park has a bar you can hang from."],
  "Hanging leg work is the hardest thing you can do for your middle and it builds grip at the same time. Ten with no swing is a real rung."),
 ("Do sit-ups every other day for a fortnight.",
  'attention', 'long',
  ["Seven sessions in fourteen days, three sets each, never to complete failure.",
   "Mix them: sit-ups, leg lifts, a hollow hold, every session.",
   "Miss one and do it the next day rather than restarting."],
  "Two clean weeks is what turns this from something you did into something you do."),
 ("Hold a hollow position for a minute, then do fifty sit-ups, in the same session.",
  'skill', 'room',
  ["Hollow first, rest two minutes, then the fifty.",
   "Both to full range, both honest.",
   "That is the ladder."],
  "Strong in a hold and strong in a movement, in the same five minutes on a floor, with no equipment bought. That is as much as this part of you needs."),
])

lib.put(d, 'fit.pullup', name='Pull-ups', size='months', line='From hanging on for ten seconds to five in a row.',
        about=("The hardest thing in the school to get the first one of, and the most satisfying. It is the "
               "one ladder here that needs something to hang from — a park bar, a beam, a strong branch, a "
               "door frame bar — and nothing else. The path is not more pull-ups, because you cannot do any "
               "yet: it is hanging, then rows under a table, then lowering yourself slowly from the top. "
               "Do those three and the first one arrives on its own."),
        rungs=[
 ("Hang from a bar with your feet off the ground for ten seconds.",
  'skill', 'kit',
  ["Hands a little wider than your shoulders, palms facing away, arms straight.",
   "Feet off the ground. Let your shoulders stretch up at first.",
   "Free option: almost every play park and outdoor gym has a bar at the right height."],
  "Grip is usually what gives out first, and it is the quickest thing to improve. Ten seconds becomes thirty within a fortnight of trying."),
 ("Hang for twenty seconds.",
  'skill', 'kit',
  ["Same hold, relaxed shoulders, breathing.",
   "If your hands hurt, that is the skin, not the strength — it toughens in a week.",
   "Two hangs of fifteen with a rest is fine on the way there."],
  "A daily hang is also the best thing there is for shoulders that have spent the day at a desk."),
 ("Hang and pull your shoulders down away from your ears, five times.",
  'skill', 'kit',
  ["Start hanging loose, then without bending your arms, pull your shoulder blades down.",
   "You rise an inch or two. Hold for two seconds, then let back down.",
   "Five slow ones. Arms stay straight throughout."],
  "This tiny movement is the first inch of a pull-up and the piece nearly everybody is missing. Learn it before you ever bend an elbow."),
 ("Hang for thirty seconds.",
  'skill', 'kit',
  ["One hang, thirty seconds, feet off the ground.",
   "Shoulders pulled down rather than up by your ears.",
   "Chalk not required. Dry hands are enough."],
  "Thirty seconds of dead hang means grip is no longer the thing stopping you, which matters because it is about to stop being the easy part."),
 ("Do five rows under a low bar or a sturdy table, feet on the floor.",
  'skill', 'kit',
  ["Lie underneath, grab the edge, body straight, arms straight at the bottom.",
   "Pull until your chest touches, then lower all the way down.",
   "Knees bent and feet flat makes it easier; legs straight makes it harder."],
  "A row is a pull-up you can already do, at whatever angle suits you. This is where the pulling strength is actually built."),
 ("Do ten rows.",
  'skill', 'kit',
  ["Same shape, chest to the edge every rep.",
   "Slower on the way down than on the way up.",
   "Straighten your legs out if ten is comfortable."],
  "If you only ever did rows you would end up with a strong back and no pull-up. They are the base, not the goal — but the base has to be there."),
 ("Do fifteen rows with your legs straight.",
  'skill', 'kit',
  ["Heels on the floor, body one straight line, chest to the bar every time.",
   "Fifteen in a row, controlled.",
   "Heels on a chair when this gets easy — that is almost a horizontal pull-up."],
  "Fifteen straight-legged rows is roughly the strength a first pull-up sits on. Most people who cannot do a pull-up cannot do this either."),
 ("Jump to the top of a pull-up and hold your chin over the bar for five seconds.",
  'skill', 'kit',
  ["Jump, or step off a bench, so your chin starts above the bar.",
   "Hold there — elbows in, chest up to the bar, shoulders down.",
   "Five seconds, then lower yourself rather than dropping."],
  "The top is the position you are trying to reach, so it is worth learning what it feels like before you can get there on your own."),
 ("Hold your chin over the bar for ten seconds.",
  'skill', 'kit',
  ["Same jump to the top, ten seconds of holding on.",
   "Chest towards the bar, not chin craned over it.",
   "Two holds of seven with a rest is fine on the way."],
  "Ten seconds at the top is worth about three ordinary pull-ups' worth of work and you can do it today."),
 ("Jump to the top and lower yourself as slowly as you can, three times.",
  'skill', 'kit',
  ["Get to the top, then take as long as you can to come down to straight arms.",
   "Five seconds is good. Ten is excellent.",
   "Rest a full minute between each. Three is plenty."],
  "You can lower far more than you can lift, which is exactly why this is how a first pull-up is built. This rung is the single most useful one on the ladder."),
 ("Lower yourself over a slow count of five, five times.",
  'skill', 'kit',
  ["Five seconds down, every time, all the way to straight arms.",
   "No dropping the last bit — control to the end is the rung.",
   "A minute's rest between each one."],
  "If the fifth one is as slow as the first, you are close. Most people find the first pull-up appears within three weeks of doing these twice a week."),
 ("Do the slow lowerings twice a week for a fortnight.",
  'attention', 'long',
  ["Four sessions in fourteen days: five slow lowerings, plus fifteen rows, plus a thirty-second hang.",
   "Never more than twice a week — this is hard on the arms and needs the recovery.",
   "Write the four sessions down and tick them off."],
  "This is the fortnight where the pull-up is actually bought. Everything before it was preparation and everything after it is counting."),
 ("Do five pull-ups with one foot resting on a chair.",
  'skill', 'kit',
  ["Chair or bench under the bar, one foot on it, using the leg just enough to keep going.",
   "Chin over the bar every rep, lower all the way down.",
   "Use less leg each week."],
  "The foot on the chair is a dial you can turn down a fraction at a time, which is far better than failing at nothing repeatedly."),
 ("Do five pull-ups with somebody holding your feet, or with a band.",
  'skill', 'with',
  ["A hand under each foot, taking just enough weight that you can finish the set.",
   "Ask them to help less on each rep.",
   "No band needed, and no band is better — a person can give you exactly what you need."],
  "This is also a good way to get somebody else onto the bar, since they will want a go once they have held your feet."),
 ("Do one pull-up on your own, chin clearly over the bar.",
  'skill', 'kit',
  ["Fresh, first thing, dead hang to start — no swinging, no kipping.",
   "Pull your shoulders down first, then bend your arms.",
   "Chin clearly over. All the way down after."],
  "This is one of the few things in life you genuinely cannot fake, and the day it arrives is a day you remember. A good many adults will never do one."),
 ("Do one pull-up on three separate days in one week.",
  'skill', 'long',
  ["One is plenty per session — do three or four singles with long rests.",
   "Strict every time. Never let the form slip to get a number.",
   "Rows and hangs on the days in between."],
  "Three separate days proves it was not a fluke and is also exactly how the second one is built."),
 ("Do two in a row.",
  'skill', 'kit',
  ["Dead hang, up, all the way down, up again without dropping off.",
   "Rest three minutes and try again rather than grinding sets.",
   "Keep doing the slow lowerings on the other days."],
  "The second one is the hardest jump on the ladder. From two onwards the numbers come much faster."),
 ("Do three in a row.",
  'skill', 'kit',
  ["Fresh, dead hang, full range.",
   "Build with singles and doubles, four or five sets, plenty of rest.",
   "Never train these to complete failure."],
  "Three is where people stop asking whether you can do a pull-up and start asking how many."),
 ("Do five across a day, in singles.",
  'skill', 'long',
  ["One every time you pass the bar. Five by bedtime.",
   "Strict every time, no rushing.",
   "Great to do on a day at a park with the family."],
  "Little and often is how this whole ladder works, and it is also how you stay fresh enough to keep adding."),
 ("Do five in a row, and show somebody the slow lowering.",
  'skill', 'with',
  ["Dead hang, five strict pull-ups, all the way down each time.",
   "Then put somebody else on the bar and teach them the slow lowering.",
   "Tell them the honest timescale: a couple of months, twice a week."],
  "Five strict pull-ups is a strong adult by any standard, from a start of hanging on for ten seconds. Teaching the lowering is the whole ladder in one gift."),
])

lib.put(d, 'fit.lift', name='Lifting', size='weeks', line='Picking a heavy thing up properly, and putting it up high.',
        about=("Getting something heavy off the floor and up onto a shelf, without hurting yourself. This is "
               "the least glamorous and most useful physical skill there is: almost every bad back in the "
               "world came from one careless lift. Everything you need is already in the house — bags, boxes, "
               "water containers, sacks of coal or compost. Carrying it any distance is its own ladder."),
        rungs=[
 ("Pick something heavy up off the floor with a straight back, and put it down again.",
  'skill', 'room',
  ["Stand close to it, feet apart, bend at the hips and knees rather than rounding your back.",
   "Grip it, take the slack out of your arms, then stand up by pushing the floor away.",
   "Set it down the same way. Lowering carelessly is how most backs go."],
  "Close to you, back straight, legs doing the work. That is the whole technique and it does not change however heavy the object gets."),
 ("Do that ten times without your back rounding once.",
  'skill', 'room',
  ["Watch yourself in a window or a mirror, or have somebody watch your back.",
   "Stop the set the moment your back rounds — that is the number, not a failure.",
   "Reset your feet and your grip before every single rep."],
  "Ten in a row is where technique either holds or shows itself up. Practising with something light and getting it perfect is the point."),
 ("Lift something the weight of your own head straight up overhead.",
  'skill', 'room',
  ["A full kettle, a heavy book, a bag with a few tins in it. About four or five kilos.",
   "Press it straight up until your arms are locked out beside your ears.",
   "Ribs down, backside squeezed — do not lean back to get it up."],
  "Overhead is the range most adults quietly lose first, and losing it is why high shelves become somebody else's job."),
 ("Lift something heavy from the floor onto a table in one smooth movement.",
  'skill', 'home',
  ["A crate, a box of books, a bag of compost.",
   "Straight back down, stand up with it, step in and set it down — no dropping, no swinging.",
   "If you have to jerk it, it is too heavy. Go lighter and do it properly."],
  "Smooth is stronger than fast. A lift that has to be snatched is a lift that is about to go wrong."),
 ("Put something heavy on a high shelf without wobbling.",
  'skill', 'home',
  ["Lift to your chest first, then press it up and onto the shelf.",
   "Get your feet under you before the weight goes overhead.",
   "Both hands stay on it until it is resting."],
  "The dangerous moment is never the lifting — it is the half second when you are reaching and the weight is out in front of you."),
 ("Carry something awkward up a full flight of stairs.",
  'skill', 'home',
  ["A box, a full laundry basket, a bag of sand — something with no good handles.",
   "Hold it high and close to your chest so you can see your feet.",
   "Go slowly. One step at a time, no rushing the last few."],
  "Awkward beats heavy for causing injuries. Everything in real life is awkward, so it is worth practising on purpose."),
 ("Lift something heavy from the floor to your shoulder in one go.",
  'skill', 'room',
  ["A sack of potatoes or compost, a heavy holdall, a bag of coal.",
   "Floor to chest, then roll it onto your shoulder and stand tall.",
   "Both hands on it, back straight, legs doing the work."],
  "Floor to shoulder is the old test of everyday strength, and it is the one movement that covers almost everything a working day asks for."),
 ("Move ten heavy things with somebody, taking the awkward end every time.",
  'kindness', 'with',
  ["A wardrobe, a sofa, a washing machine, boxes, a bed frame.",
   "Take the end that is harder to hold or has to go backwards up the stairs.",
   "Agree the plan out loud before you lift: where it is going, who steps first."],
  "Lifting with somebody is a skill of its own: the talking matters more than the strength, and the person who takes the awkward end is the one who gets asked back."),
 ("Lift something half your own weight off the floor, ten times.",
  'skill', 'kit',
  ["A well-packed rucksack, two water containers tied together, a heavy case.",
   "Straight back, close to you, legs pushing the floor away.",
   "Stop at the first rounded back rather than at ten."],
  "Half your bodyweight lifted ten times is a genuinely strong back and hips, and every bit of it was built with household objects."),
 ("Lift something your own bodyweight off the floor.",
  'skill', 'kit',
  ["A very full case, a heavy person on a chair with two of you, a loaded sack barrow.",
   "One clean lift, an inch off the ground is enough, straight back throughout.",
   "If you cannot keep your back straight, it is too heavy. That is not a rung worth forcing."],
  "Your own bodyweight off the floor is a proper benchmark. It is also the rung to be sensible on: nothing here is worth a hurt back."),
 ("Lift something the weight of a small child overhead, five times.",
  'skill', 'kit',
  ["Fifteen kilos or so — a full rucksack, a water container, a bag of coal.",
   "Chest first, then press up, arms locked out beside your ears.",
   "Ribs down, no leaning back."],
  "Being able to put something heavy over your head is what keeps you independent in a house with high shelves, lofts and roof boxes."),
 ("Help somebody move house for a whole day, and still be useful at the end of it.",
  'kindness', 'out',
  ["Offer before you are asked. Turn up early with gloves.",
   "Take the awkward end, pace yourself, and keep your technique when you are tired.",
   "The rung is the last hour, not the first."],
  "Technique when you are fresh is easy. Technique in the last hour, when everybody is tired and careless, is what this ladder was actually for."),
])

lib.put(d, 'body.strength', name='Carrying', size='months', line='From two heavy bags to a person on your back.',
        about=("Strength that goes somewhere. Lifting is getting a load off the ground; carrying is moving it "
               "down a street, up a hill or up two flights of stairs, and it is the sort of strength that "
               "actually shows up in a life — shopping, moving house, a child asleep on your shoulder, "
               "somebody who has turned an ankle. No equipment: bags, water containers, sacks, and people."),
        rungs=[
 ("Carry a full bag in each hand the length of your street.",
  'skill', 'out',
  ["Two shopping bags, two full water containers, two bags of books.",
   "Stand tall, shoulders back, walk normally. Do not lean to one side.",
   "If you have to stop, they are too heavy — go a bit lighter and walk the whole way."],
  "Two even loads are the easiest way to carry weight and the best place to start. The goal is always to walk normally, not to survive."),
 ("Carry something heavy in one hand the same distance, then swap.",
  'skill', 'out',
  ["One bag, one side, the whole length, then the same on the other side.",
   "Do not lean away from it — stay upright and let your middle do the holding.",
   "Shorter distance if you find yourself tipping."],
  "One-sided carrying is what really trains the sides of your middle, and it is what most of real life is: one heavy bag and a door to open."),
 ("Carry something awkward up a full flight of stairs.",
  'skill', 'home',
  ["A box, a laundry basket, a bag of sand, a bedside table.",
   "High and close to your chest so you can see the steps.",
   "One step at a time. No rushing the last three."],
  "Stairs with something awkward is where carelessness costs most. Slow is not weakness here; it is the skill."),
 ("Carry two heavy bags for a hundred metres without setting them down.",
  'skill', 'out',
  ["Count the distance out — about a minute and a half of ordinary walking.",
   "Set your grip properly before you start rather than adjusting on the move.",
   "Breathe. People hold their breath when carrying and it is why they stop."],
  "A hundred metres is roughly a car park to a front door. This is the rung that makes a big shop a non-event."),
 ("Carry something heavy on one shoulder for fifty metres.",
  'skill', 'out',
  ["A sack of compost or coal, a heavy holdall, a rolled carpet.",
   "Up to the chest first, then onto the shoulder, one hand steadying it.",
   "Swap sides halfway if it is comfortable."],
  "The shoulder carry is how heavy things were moved for most of history, and it is far easier than it looks once the load is properly settled."),
 ("Carry a full rucksack for a solid hour's walk.",
  'skill', 'out',
  ["Ten to fifteen kilos: water containers, books, tins, whatever is to hand.",
   "Straps tight, load high and close to your back.",
   "An hour, one walk, no sitting down. Rain is fine."],
  "A loaded walk is the single best bit of training in this whole ladder and it doubles as a day out. Take it somewhere worth looking at."),
 ("Carry something heavy in each hand for two hundred metres.",
  'skill', 'out',
  ["Twice the distance of rung four, same load or heavier.",
   "Pick a landmark and walk to it rather than counting steps.",
   "Set down once and finish, if you must — then do it unbroken next time."],
  "Grip usually fails before the rest of you does. That is normal, it improves fast, and it is worth having for its own sake."),
 ("Carry a child on your shoulders for a mile.",
  'kindness', 'with',
  ["Hands holding their shins, their hands on your head, both of you agreeing to the plan.",
   "Duck under branches early rather than late.",
   "No child to hand? A rucksack with fifteen kilos in it for the same mile."],
  "This is the carrying that everybody actually wants to be able to do. It is also fifteen or twenty kilos for twenty minutes, which is real work."),
 ("Carry two heavy bags up two flights of stairs without setting them down.",
  'skill', 'home',
  ["Steady pace from the first step. Do not start fast.",
   "Even loads, upright, eyes on the steps.",
   "If your grip is going, that is the rung for another fortnight."],
  "Stairs with a load are about three times as hard as flat ground and are exactly what a house move consists of."),
 ("Carry half your own bodyweight for fifty metres.",
  'skill', 'out',
  ["Split across two hands, or a loaded rucksack plus a bag.",
   "Set up properly, walk tall, breathe.",
   "Do not chase this one if your back complains — go back a rung."],
  "Half your bodyweight is a serious carry and it is the point where people start volunteering you for things."),
 ("Carry somebody your own size ten metres on your back.",
  'skill', 'with',
  ["They climb on from a step or a wall so you are not lifting them from the ground.",
   "Arms under their thighs, lean forward a little, walk tall.",
   "Agree how they get off before you start."],
  "A piggyback is a ridiculous amount of fun and a genuinely heavy carry. Ten metres is enough to find out how heavy a person is."),
 ("Do the carries on three separate days in one week.",
  'attention', 'long',
  ["Two or three carries a session: two bags, one shoulder, one loaded walk.",
   "Ten or fifteen minutes is plenty.",
   "Write the three days down and tick them off."],
  "Carrying builds quickly because it is the kind of work your body was built for. Three sessions a week is a month of noticeable change."),
 ("Carry somebody your own size twenty-five metres.",
  'skill', 'with',
  ["On your back, arms under the thighs, upright rather than bent over.",
   "Short steps, steady breathing, no rushing.",
   "Put them down properly rather than dropping them."],
  "Twenty-five metres with a person on your back is the distance that turns this from a game into a thing you could do if you had to."),
 ("Carry a loaded rucksack up a hill without stopping.",
  'skill', 'out',
  ["Ten to fifteen kilos, any decent hill, all the way to the top.",
   "Short steps and a slow steady pace beat charging and stopping.",
   "No hill nearby? Two flights of stairs, five times over, with the pack on."],
  "Hills with weight are the oldest training there is. It also happens to be how you end up at the top of somewhere worth seeing."),
 ("Carry two full water containers a mile.",
  'skill', 'out',
  ["Ten litres a side is twenty kilos. Five litres a side if that is too much.",
   "Set down as many times as you need the first time, fewer the next.",
   "Water is free and you can pour it out at the end."],
  "The cheapest heavy training in the world, and the load gets exactly as heavy as you decide. A mile with it is a proper morning's work."),
 ("Carry somebody your own size fifty metres.",
  'skill', 'out',
  ["Fifty metres, on your back, no setting them down.",
   "Find your rhythm in the first ten steps and keep it.",
   "Somebody else nearby, just in case."],
  "Fifty metres is far enough to get somebody out of a field, off a beach or to the end of a road. That is the reason this rung exists."),
 ("Carry a heavy load for half an hour over rough ground.",
  'skill', 'out',
  ["A loaded rucksack, a field, a beach, a forest path.",
   "Uneven ground makes everything harder and it is the point.",
   "Watch your feet and slow down on the descents."],
  "Rough ground works your ankles, your balance and your attention all at once. Flat pavements never will."),
 ("Move a household with somebody for a whole day, and still be useful at the end.",
  'kindness', 'out',
  ["Offer before you are asked, turn up early, bring gloves.",
   "Take the awkward end and keep your technique when you are tired.",
   "The rung is the last hour, not the first."],
  "Everything on this ladder was built for this day. The person who is still careful and cheerful at six o'clock is the one everybody remembers."),
 ("Carry a loaded pack for a full day's walk.",
  'skill', 'out',
  ["Ten kilos or so, six or seven hours of walking, food and water in the pack.",
   "Start slower than you want to. Eat before you are hungry.",
   "Any long marked path, any decent hill day."],
  "A day under a pack is where carrying stops being training and becomes a way of getting somewhere. This is the rung that opens the outdoors."),
 ("Teach somebody how to lift and carry without hurting themselves.",
  'kindness', 'with',
  ["Close to you, back straight, legs doing the work, no twisting under load.",
   "Watch them do it and correct the back before the weight goes up.",
   "Show them the awkward-end rule and the agree-the-plan-first rule."],
  "Almost nobody is ever taught this and almost everybody hurts their back at some point. Half an hour of your time can spare somebody that entirely."),
])

lib.save(d)
lib.report(d, ['fit.situp','fit.pullup','fit.lift','body.strength'])
