# -*- coding: utf-8 -*-
"""Baking, the little one's kitchen ladder, and the whole Rest and recovery path.
   Sleep was written half at a child and half at a grown-up; it now reads as one
   thing either of them can climb. Breath carries the safety rule it was missing."""
import lib
d = lib.load()

lib.put(d, 'food.bake', name='Baking', size='months',
        line='From weighing accurately to a loaf of your own, and selling what you made.',
        about=("Baking is chemistry that you get to eat, and unlike cooking it rewards exactness rather than "
               "judgement, which makes it the better one to learn with children. The ladder goes from a packet "
               "mix to a proper loaf of bread from flour, water and salt — which costs about thirty pence and "
               "beats anything in a shop — and ends by selling what you made to somebody who is not related "
               "to you, which is a different kind of nerve entirely."),
        rungs=[
 ("Weigh five things accurately on a scale, to the gram.",
  'attention', 'kit',
  ["Bowl on the scale, zero it, then add. Zero it again for the next thing.",
   "Get it exact rather than close. Baking is the one place where close is not good enough.",
   "No scale? Kitchen scales are a few pounds second hand and every charity shop has one."],
  "Cooking forgives, baking does not. Everything above this rung depends on the weighing being honest."),
 ("Bake something from a packet mix, exactly as it says.",
  'skill', 'home',
  ["Read it all the way through first. Then follow it to the letter.",
   "Oven on early — it takes fifteen minutes to get properly hot.",
   "Set a timer and check five minutes before it goes off."],
  "A packet mix takes all the decisions away so that you learn the oven, the tin and the timing without anything else to go wrong."),
 ("Line and grease a tin so nothing sticks.",
  'attention', 'home',
  ["Butter the tin, then a circle of baking paper in the bottom, then butter that too.",
   "For a loaf tin, a long strip up and over both ends acts as handles.",
   "No paper? Butter and a dusting of flour, tapped out."],
  "More home baking is ruined at the turning-out stage than at any other. Two minutes of lining saves the whole thing."),
 ("Bake something by following a written recipe on your own.",
  'skill', 'home',
  ["Everything weighed and lined up before you start.",
   "Follow it exactly, even the bits you would change.",
   "Write on the recipe afterwards what you noticed."],
  "Follow it exactly once before you ever improvise. You cannot tell what a change did unless you know what the original does."),
 ("Rub butter into flour until it looks like breadcrumbs.",
  'skill', 'home',
  ["Cold butter, cut into small cubes, straight from the fridge.",
   "Fingertips only, lifting the mixture up and letting it fall as you rub.",
   "Stop when it looks like coarse breadcrumbs — a few bigger lumps are fine."],
  "Cold hands and cold butter. This one technique is the base of scones, shortbread, crumble and pastry, so it is worth ten minutes of practice."),
 ("Make scones or shortbread that come out right.",
  'skill', 'home',
  ["Handle the dough as little as possible — the less you work it the lighter it is.",
   "Hot oven, high shelf, and do not open the door for the first ten minutes.",
   "Cut straight down with the cutter, no twisting, or they rise crooked."],
  "The first thing you will make that people ask for again. It is also the quickest: twenty minutes from a cold kitchen to something on a plate."),
 ("Know when something is done without cutting it open.",
  'attention', 'home',
  ["A skewer into the middle comes out clean. A sponge springs back when pressed.",
   "Bread sounds hollow when you knock the bottom of it.",
   "Colour first, then the test. Pale means underdone whatever the timer says."],
  "Ovens all lie by ten or twenty degrees. Learning the tests rather than trusting the timer is what makes your baking work in anybody's kitchen."),
 ("Bake a sponge that rises.",
  'skill', 'home',
  ["Butter and sugar beaten until genuinely pale and fluffy — a good five minutes.",
   "Eggs added a little at a time so it does not split.",
   "Flour folded in gently at the end. Beating here knocks the air out."],
  "A risen sponge is air, and the air went in during the beating. This is the rung that teaches why a method is in the order it is in."),
 ("Bake something twice, and make the second one better.",
  'attention', 'home',
  ["Write down one change before you forget: five minutes less, a little more salt, a hotter oven.",
   "Same recipe, one change only, within a fortnight.",
   "Note which was better."],
  "One change at a time is the only way to learn anything from your own baking. Two changes and you will never know which did it."),
 ("Make a dough and knead it for ten full minutes.",
  'skill', 'home',
  ["Timer on. Ten minutes is much longer than it feels — most people stop at three.",
   "Push it away with the heel of your hand, fold it back, turn it a quarter, repeat.",
   "It goes from a shaggy lump to smooth and springy. That change is what you are looking for."],
  "Kneading is the whole of bread and there is no shortcut worth having. Ten minutes of it is also a remarkably good way to be in a bad mood less."),
 ("Make a loaf of bread from flour, water, salt and yeast.",
  'skill', 'home',
  ["Four ingredients only. Nothing else belongs in a loaf.",
   "Knead ten minutes, rise until doubled, knock back, shape, rise again, bake hot.",
   "It costs about thirty pence and takes fifteen minutes of actual work spread over an afternoon."],
  "A shop loaf has a label with twenty things on it. Yours has four. This one rung is the whole argument of Real food, made edible."),
 ("Make a loaf where the crumb is even all the way through.",
  'skill', 'home',
  ["Knock the air out properly before the second rise, and shape it tightly.",
   "Do not let the second rise go too far — it should spring back slowly when pressed.",
   "Cut it only when it is cool, however hard that is."],
  "Big holes at the top and dense at the bottom is the classic second loaf. Proper shaping and not over-proving is the fix."),
 ("Bake something with a filling that does not leak.",
  'skill', 'home',
  ["Cold pastry, cold filling, and seal the edges with a wet finger and a fork.",
   "Cut a hole or two in the top so the steam has a way out.",
   "Do not overfill. Everybody overfills."],
  "Leaks come from steam with nowhere to go. A couple of slits in the lid is the difference between a pie and a tray to scrub."),
 ("Ice or decorate something so it looks like it was meant to.",
  'skill', 'home',
  ["Completely cold before any icing goes near it, or it slides off.",
   "A thin first coat to catch the crumbs, then the real coat on top.",
   "Simple and neat beats elaborate and messy every time."],
  "Looking deliberate is mostly patience: cold cake, thin first coat, one colour done neatly. It doubles the pleasure for the person receiving it."),
 ("Bake something without looking at the recipe.",
  'skill', 'room',
  ["Pick the thing you have made most often.",
   "Write the recipe out from memory first, then bake it and check.",
   "Whatever you got wrong is the bit you never actually learned."],
  "Having one thing in your head that you can make in anybody's kitchen with no book is worth more than twenty recipes you can follow."),
 ("Bake for somebody's birthday.",
  'kindness', 'home',
  ["Ask what they actually like rather than baking what you like making.",
   "Make it the day before so you are not rushing.",
   "Bake a small test version first if it is a new one."],
  "A baked thing made by a person is one of the few gifts nobody has ever had too many of, and it costs about three pounds."),
 ("Work out what a batch costs you to make.",
  'attention', 'room',
  ["Weigh the flour, butter, sugar and eggs you used and price each from the receipt.",
   "Add something for the electricity and the paper.",
   "Divide by the number of pieces."],
  "This is where baking meets Money and value, and the numbers usually surprise people in both directions. You cannot price anything until you know this."),
 ("Bake to order for somebody else, to exactly what they asked for.",
  'skill', 'with',
  ["Write down what they asked for and read it back to them.",
   "Agree the day and the time before you agree anything else.",
   "Deliver it when you said, not when it is convenient."],
  "Somebody else's specification is a different job from your own baking. Getting the brief right, and on time, is most of what being paid for anything is."),
 ("Price what you baked and sell it to people who are not related to you.",
  'courage', 'out',
  ["Cost plus your time, then a real price, written on a card.",
   "A stall, a car boot, a school fair, a sign at the gate, a message to the street group.",
   "Say the price out loud without apologising for it."],
  "The nerve is not in the baking, it is in saying the number. That is the rung. Ten pounds earned from something you made changes how you see your own hands."),
 ("Teach somebody to bake one thing, start to finish, hands off.",
  'kindness', 'with',
  ["Your hands behind your back. Say it, do not do it.",
   "Let them make the mistakes — the crooked scones teach more than your perfect ones.",
   "They take the whole batch home."],
  "Hands off is the hard part and the whole rung. Something somebody made themselves, badly, with you beside them, is what makes them a baker."),
])

lib.put(d, 'food.kitchen', name='In the kitchen', size='weeks', frm=4,
        line='From four, beside you. Hands washed, then stirring, spreading, cracking and making.',
        about=("For a child of about four and upwards, with a grown-up beside them. Children want to be in "
               "the kitchen long before we let them, and a four-year-old can genuinely stir, pour, peel a "
               "satsuma, crack an egg and make a sandwich for somebody else. Every rung here is a real job "
               "that actually needed doing, which is the whole point: children can tell the difference "
               "between helping and being given something to keep them busy."),
        rungs=[
 ("Wash your hands properly before you touch any food.",
  'skill', 'with',
  ["Warm water, soap, and long enough to sing something short.",
   "Backs of the hands and between the fingers, not just the palms.",
   "Dry them on a towel, not on your clothes."],
  "Start every single session with this and it becomes automatic within a fortnight. Do it yourself beside them rather than telling them to."),
 ("Put an apron on by yourself.",
  'skill', 'with',
  ["Over the head first, then the ties.",
   "A tea towel tucked in at the neck works perfectly well as an apron.",
   "Let them struggle with the ties for a while before you help."],
  "The apron is the signal that this is a proper job, not playing. Children take the whole session more seriously with one on."),
 ("Stir something in a bowl until it is all mixed and nothing is left at the bottom.",
  'skill', 'with',
  ["A big bowl on a damp cloth so it does not spin.",
   "Show them how to go round the bottom edge where it hides.",
   "Let them check by lifting the spoon and looking."],
  "Give them the checking as well as the stirring. A child who has been shown how to tell when a job is done will do it properly without being watched."),
 ("Pour from a small jug into a bowl without spilling it.",
  'skill', 'with',
  ["Small jug, half full. Both hands.",
   "Slow and close — hold the jug low, near the bowl.",
   "Practise with water at the sink first, where spills do not matter."],
  "Practising with water first is the trick for all of this. Ten free goes at the sink is worth more than one careful go with the eggs."),
 ("Spread butter on a slice of bread, right to the edges, without tearing it.",
  'skill', 'with',
  ["Soft butter, left out beforehand. Hard butter tears the bread and they get cross.",
   "A round-ended knife, spreading from the middle outwards.",
   "Look at the corners together at the end."],
  "The corners are the standard, and it is a standard a four-year-old can see for themselves. That is what makes it a good first job."),
 ("Peel a banana or a satsuma all by yourself.",
  'skill', 'with',
  ["Start the satsuma peel for them with your thumbnail, then hands off.",
   "A banana opens more easily from the bottom than the stalk end.",
   "Their fruit to eat afterwards."],
  "Let them finish it even when it takes three minutes and makes a mess. Finishing it themselves is the entire rung."),
 ("Crack an egg into a bowl.",
  'skill', 'with',
  ["Tap it firmly on the flat worktop, not on the edge of the bowl — it shatters less.",
   "Both thumbs in the crack, open it over the bowl.",
   "Use a separate small bowl so a bad one does not spoil the mixture."],
  "The small bowl is how you let them do it without any risk to the meal, which means you can say yes rather than 'not this time'."),
 ("Pick the bits of shell out.",
  'attention', 'with',
  ["A bigger piece of shell picks up a small one far more easily than fingers do.",
   "Look properly rather than quickly.",
   "Their job to say when it is clear."],
  "Fixing your own mistake without anybody being cross about it is a small, important lesson, and this is the safest possible place to learn it."),
 ("Weigh something on the scales and say the number out loud.",
  'skill', 'with',
  ["Bowl on, zero it together, then spoon it in slowly.",
   "Let them stop at the right number rather than you saying stop.",
   "Numbers on a scale are real numbers doing a real job."],
  "This is reading, counting and a bit of chemistry, and none of it feels like a lesson. It is also the first rung of the Baking ladder."),
 ("Make a sandwich and give it to somebody to eat.",
  'kindness', 'with',
  ["Their choice of filling, within reason.",
   "Cut it however they think is best.",
   "They carry it and hand it over themselves."],
  "The handing-over is the important half. Making something that another person actually eats is the first time a child feeds somebody, and they know it."),
 ("Wipe the table and put your things in the sink afterwards.",
  'kindness', 'with',
  ["Damp cloth, and show them the crumbs they missed rather than doing it after them.",
   "Everything they used goes in the sink or the dishwasher.",
   "Apron off and hung up last."],
  "Clearing up is part of the job, not a punishment at the end of it. Start it at four and it is never a battle at fourteen."),
 ("Help make one whole thing for everybody's tea.",
  'kindness', 'with',
  ["Pick something with jobs they can genuinely do: a tray bake, a crumble, soup, buns.",
   "Tell everybody at the table who made it.",
   "Let them serve it out."],
  "Say their name out loud when the food goes on the table. Being useful to the whole family, publicly, is what they are actually after."),
])

lib.put(d, 'calm.sleep', name='Sleep', size='weeks',
        line='From going to bed without a fight to running your own rest and fixing somebody else’s.',
        about=("Sleep is the one thing that makes every other ladder in the school easier, and it is the "
               "easiest of all of them to fix, because almost all of it comes down to a handful of habits "
               "that cost nothing: the same waking time, daylight in the morning, a dark cool room, and the "
               "last half hour away from a screen. It works the same way for a child of six and an adult of "
               "forty, which is why this ladder is written for both."),
        rungs=[
 ("Go to bed at the time you said you would, three nights running.",
  'skill', 'long',
  ["Decide the time in the morning, not at eleven at night.",
   "Set an alarm for going to bed, not only for getting up.",
   "Three nights, written down and ticked off."],
  "The hard part of bedtime is never the bed, it is stopping whatever you are doing. An alarm at the start of the evening does the deciding for you."),
 ("Get up at the same time three days running.",
  'skill', 'long',
  ["Same time every one of the three, including any day off.",
   "Feet on the floor and curtains open within a minute of the alarm.",
   "Whatever time you went to bed."],
  "The waking time is the lever, not the bedtime. Fix when you get up and your body sorts out when you fall asleep, usually within a week."),
 ("Get daylight on your face in the first hour of the morning, every day for a week.",
  'attention', 'out',
  ["Outside, not through a window. Ten minutes is plenty.",
   "Even a grey morning outdoors is many times brighter than any indoor room.",
   "Walk to the shop, stand in the garden, walk somebody to school."],
  "This is the strongest and cheapest thing on the whole ladder. Morning light is what sets the clock that decides when you feel sleepy fourteen hours later."),
 ("Keep screens out of the last half hour before bed, for a week.",
  'courage', 'home',
  ["Phone on charge in another room, or at least across the room.",
   "A book, a bath, tidying, talking, drawing — anything that is not a lit rectangle.",
   "Seven nights."],
  "It is the endless scrolling more than the light: a screen never reaches the end of itself, so it never lets you stop. A book has pages that run out."),
 ("Go to bed at your time seven nights running.",
  'skill', 'long',
  ["Same time, including at the weekend.",
   "Start the last half hour early enough that the time is actually possible.",
   "Seven nights, ticked off."],
  "A week is where this stops taking willpower. After about five nights the sleepiness starts arriving on its own, which is the whole point."),
 ("Notice how you feel after a bad night, and say so out loud.",
  'courage', 'room',
  ["Name it plainly to somebody: short-tempered, foggy, weepy, hungry.",
   "Do it on the day, not afterwards.",
   "No excuses attached to it, just the fact."],
  "Joining up a bad night with a bad day is what makes anybody bother to fix their sleep. Children in particular have usually never been told the two are connected."),
 ("Get up at the same time seven days running.",
  'skill', 'long',
  ["Every day, including Saturday and Sunday.",
   "Curtains open, outside within the hour.",
   "If you had a bad night, get up anyway — the lie-in is what keeps the cycle going."],
  "The weekend lie-in is what undoes most people. Two late mornings is the same as flying two time zones west and back every single week."),
 ("Make your room properly dark and properly cool for a week.",
  'attention', 'home',
  ["Cover or turn off every little light: standby lamps, chargers, clocks.",
   "Cooler than feels right — a window open, one fewer blanket.",
   "A cheap blackout blind or even a towel over the curtain rail works."],
  "Dark and cool are the two conditions your body is actually waiting for. An hour of work on your room pays back every night for years."),
 ("Keep screens out of the last full hour before bed, for a fortnight.",
  'courage', 'home',
  ["Phone charging in another room overnight. Buy an alarm clock if that is what it takes.",
   "Decide what the hour is for before you need it: a book, a bath, a walk, a jigsaw.",
   "Fourteen nights."],
  "Most people find the hour itself becomes the best part of the day within a fortnight, which nobody expects when they start."),
 ("Have the same last twenty minutes every night for a fortnight.",
  'attention', 'long',
  ["Same order every night: teeth, room ready, curtains, a few pages, light off.",
   "Boring on purpose. The sameness is the medicine.",
   "Fourteen nights of the identical routine."],
  "A routine works because it stops being a decision. Children are given one and grown-ups think they have outgrown it; they have not."),
 ("Find out how many hours you actually need, by trying it.",
  'attention', 'long',
  ["A week where you go to bed at the same time and wake without an alarm.",
   "Write down the hours each night and how the day went.",
   "A holiday week or a quiet week is the time to do this."],
  "Almost everybody guesses wrong about their own number. Knowing it means you can plan a week properly instead of hoping."),
 ("Run your own rest for a month, and then help somebody else fix theirs.",
  'kindness', 'with',
  ["A month of your own times, your own routine, nobody reminding you.",
   "Then sit down with somebody and go through it: waking time, morning light, dark room, last half hour.",
   "Give them the one that will help them most, not all four at once."],
  "One change at a time is how you help somebody. The waking time and the morning light are the two that do most of the work, so start them there."),
])

lib.put(d, 'body.breath', name='Breath', size='weeks',
        line='From ten slow breaths to two minutes held, calmly, and teaching it to somebody.',
        about=("Your breathing is the one part of your body that runs itself and that you can also take hold "
               "of, which makes it the fastest way there is to calm yourself down on purpose. This ladder is "
               "half calm and half capacity: slow breathing that you can use before anything frightening, and "
               "breath holds that climb to two minutes. One safety rule runs through all of it, and it is not "
               "negotiable: never practise any of this in water, or near water, ever."),
        rungs=[
 ("Take ten slow breaths through your nose, with your mouth shut.",
  'attention', 'room',
  ["Sitting up, shoulders down, mouth closed the whole time.",
   "In through the nose to a count of four, out through the nose to a count of six.",
   "Feel your stomach move rather than your chest."],
  "Breathing through your nose warms, filters and slows the air. Most of us mouth-breathe all day without noticing, and simply closing your mouth is a real change."),
 ("Breathe out for twice as long as you breathe in, twenty times.",
  'attention', 'room',
  ["In for four, out for eight. Count it in your head.",
   "Do not force the out-breath — let it be long and loose.",
   "Twenty rounds is about four minutes."],
  "The long out-breath is the switch. It is the one thing that reliably slows a racing heart, and it works within about a minute."),
 ("Breathe in for four, hold four, out for four, hold four — ten rounds.",
  'attention', 'room',
  ["Square, even counts. Sitting up, eyes closed if you like.",
   "If four is a struggle, use three.",
   "Ten rounds is about three minutes."],
  "This is the pattern soldiers and divers are taught for staying steady under pressure, and it is simple enough that a child of seven can use it in a dentist's chair."),
 ("Hold your breath for thirty seconds, sitting still.",
  'skill', 'room',
  ["Sitting down, on dry land, never in or near water.",
   "Two or three slow breaths first, then a normal breath in, then hold.",
   "Stop the moment it is genuinely unpleasant. This is not a competition."],
  "On land, a breath hold is completely safe and simply uncomfortable. In water it is dangerous, and people have drowned practising exactly this. Never in water."),
 ("Use the slow breathing before something you are nervous about.",
  'courage', 'room',
  ["Twenty long out-breaths, in the five minutes before the thing.",
   "A phone call, a talk, a test, a difficult conversation, a needle.",
   "Then go and do the thing."],
  "Here is where this stops being an exercise and becomes a tool. Having something to actually do with your hands and your lungs while you wait is half the battle."),
 ("Hold your breath for forty-five seconds.",
  'skill', 'room',
  ["Sitting still, on dry land, timer running.",
   "Relax your face and shoulders. Tension burns air.",
   "The first urge to breathe is not the end — it comes far earlier than you need to stop."],
  "Most of the improvement here is not lung capacity, it is learning that the first strong urge to breathe can be sat through calmly. That transfers to a lot of things."),
 ("Do the slow breathing every day for a week.",
  'attention', 'long',
  ["Five minutes, same time each day. First thing or last thing.",
   "Any of the patterns you have learned.",
   "Seven days, ticked off."],
  "Practising when you are calm is what makes it available when you are not. Nobody can learn a new way of breathing in the middle of a panic."),
 ("Hold your breath for one minute.",
  'skill', 'room',
  ["Sitting or lying, never in water.",
   "A few slow breaths first, then a full but not stuffed breath in.",
   "Let it out slowly when you finish rather than gasping."],
  "A minute sounds impossible before you have done thirty seconds and easy afterwards. Almost everybody gets there within a fortnight of trying every few days."),
 ("Slow your own pulse down on purpose, and count it before and after.",
  'skill', 'room',
  ["Find your pulse at your wrist or your neck and count the beats for thirty seconds. Double it.",
   "Three minutes of long out-breaths, four in and eight out.",
   "Count it again."],
  "Watching a number you thought was out of your control move because you decided it should is the moment this ladder lands. Ten or fifteen beats is a normal change."),
 ("Hold your breath for ninety seconds.",
  'skill', 'room',
  ["Dry land, sitting still, somebody nearby if you like.",
   "Stay loose. Swallowing once is normal and buys you time.",
   "Never do this standing at the edge of anything, or in a bath."],
  "By now the hold is almost entirely a mental job. The lungs are not the limit; the willingness to be uncomfortable calmly is."),
 ("Hold your breath for two minutes.",
  'skill', 'room',
  ["Lying down, warm, still, on a day you are rested.",
   "Slow breathing for two minutes first, then the hold.",
   "Stop whenever you want to. Nothing here is worth pushing into feeling unwell."],
  "Two minutes is the end of this ladder and it is a genuinely surprising thing to own. Longer than this is a thing for trained people with trained supervision, not for an app."),
 ("Teach somebody the slow breathing until they can do it without you.",
  'kindness', 'with',
  ["The long out-breath first. That is the one that works.",
   "Do it with them rather than describing it.",
   "Give them one moment to use it for: before bed, before a test, when they are angry."],
  "A child who is given this at six has it for life, and it is the single most useful thing on this ladder. Give them the out-breath and one moment to use it, and nothing else."),
])

lib.put(d, 'water.cold', name='Cold water', size='weeks', place='water',
        line='From thirty seconds at the end of a shower to a calm four minutes in the sea.',
        about=("Getting into cold water is the shortest route there is to finding out that you can do "
               "something you do not want to do, and it takes two minutes. It starts in your own shower, "
               "which costs nothing, and moves out to the sea or a lough. The whole skill is the breathing: "
               "cold water makes you gasp, and everything else here is learning to take hold of that. Never "
               "get into open water alone, never after drinking, and always have dry warm clothes waiting."),
        rungs=[
 ("Finish a shower with thirty seconds of cold.",
  'courage', 'home',
  ["Normal warm shower, then turn it to full cold for the last thirty seconds.",
   "Head and shoulders under it, not just your feet.",
   "Breathe out slowly and steadily. Do not hold your breath."],
  "Thirty seconds, in your own bathroom, costing nothing. The gasp lasts about ten seconds and then it is simply cold, which is a very different thing."),
 ("Finish a shower with a full minute of cold, three days running.",
  'courage', 'home',
  ["Same routine, longer. A minute is not twice as hard as thirty seconds.",
   "Slow long out-breaths all the way through.",
   "Three days, ticked off."],
  "By the third morning you will notice that the dread beforehand is bigger than the cold itself. That gap is the lesson this ladder is really teaching."),
 ("Stand in the sea or a lough up to your ankles for one minute.",
  'courage', 'out',
  ["Somewhere you know, with somebody with you.",
   "Shoes off, trousers rolled. A minute on the clock.",
   "Any beach, any weather. Free everywhere in this country."],
  "Cold feet on a cold day is worse than people expect and is the honest start. The sea is a different thing from a shower and deserves its own first rung."),
 ("Stand in up to your knees for a minute.",
  'courage', 'out',
  ["Walk in slowly rather than dashing.",
   "Long out-breaths from the moment the water touches you.",
   "Dry socks and shoes waiting on the sand."],
  "The cold moves up your body in stages and each stage has its own gasp. Taking them one at a time is exactly how the whole ladder is climbed."),
 ("Get in up to your waist and stay calm for a minute.",
  'courage', 'out',
  ["This is the one that makes people squeal. Go slowly and keep breathing out.",
   "Hands out of the water at first — hands and wrists feel it worst.",
   "Somebody with you on the shore."],
  "Waist deep is the real test of the breathing, because this is where the gasp reflex is strongest. Slow out-breaths beat it every time."),
 ("Get in up to your shoulders and control your breathing.",
  'courage', 'out',
  ["Lower yourself in rather than jumping. Never dive into cold water.",
   "The first thirty seconds are the worst and then it settles.",
   "Out as soon as the breathing is under control — this rung is not about staying in."],
  "Cold water shock is a real thing and it is at its worst in the first thirty seconds. Getting in slowly and breathing out is what makes it safe."),
 ("Get warm again properly afterwards, and write down how you did it.",
  'attention', 'out',
  ["Dry off completely and dress from the top down, hat on early.",
   "Something warm to drink, and move about — walk, do not sit in the car.",
   "No hot shower straight away; warm up from the inside first."],
  "Getting warm again is the part people get wrong, and the cold keeps coming for twenty minutes after you are out. Plan this before you get in, not after."),
 ("Stay in up to your shoulders for one full minute.",
  'courage', 'out',
  ["Timer on the shore. Somebody watching.",
   "Still, calm, breathing slowly. Not swimming about.",
   "Out on the minute, whatever it feels like."],
  "A minute in properly cold water is a real thing to have done. Get out on time rather than proving anything — the people who get into trouble are the ones who stay longer than they planned."),
 ("Go in on a day you did not feel like it.",
  'courage', 'out',
  ["Decide the night before and go, regardless of the weather or the mood.",
   "Do not renegotiate with yourself at the car park.",
   "Same routine: in slowly, breathe out, warm up properly."],
  "This is the rung the whole ladder exists for. Doing the thing you had decided to do, on a day you did not fancy it, is a skill that has nothing to do with water."),
 ("Stay in for two minutes and get properly warm again afterwards.",
  'courage', 'out',
  ["Two minutes, timed, then straight out and into the warming routine you wrote down.",
   "Watch for shivering that will not stop — that is the point to stop for the day.",
   "Never alone, and never after a drink."],
  "Longer is not better in cold water. Two minutes with a good warm-up afterwards is worth far more than five minutes and an afternoon of shivering."),
 ("Go in once a week for a month, whatever the weather.",
  'attention', 'long',
  ["Four dips, one a week, written in the calendar in advance.",
   "Same place, with the same person, so it needs no arranging.",
   "Whatever the weather does."],
  "A month of this changes how you meet cold, rain and discomfort generally. It also tends to become the thing you look forward to most in the week."),
 ("Take somebody else through their first cold dip, safely.",
  'kindness', 'with',
  ["Tell them about the gasp before it happens so it does not frighten them.",
   "In slowly, never diving, long out-breaths, and out on an agreed time.",
   "Their warm clothes, hat and hot drink ready before they get in."],
  "Talking somebody through their first thirty seconds is a genuinely useful thing to be able to do, and safety is the whole of it: slow in, breathe out, agreed time, warm afterwards."),
])

lib.save(d)
lib.report(d, ['food.bake','food.kitchen','calm.sleep','body.breath','water.cold'])
