# -*- coding: utf-8 -*-
"""The Food path, after Real food part one and part two (which are already written).
   Fasting now starts where part two finishes instead of repeating its twelve- and
   sixteen-hour rungs, and the kitchen ladders get a note each."""
import lib
d = lib.load()

lib.put(d, 'calm.fast', name='Fasting', size='months', frm=18, after='food.real2',
        line='For grown-ups. From a comfortable sixteen hours to thirty-six, done properly.',
        about=("Real food part two took you to a sixteen-hour window and one twenty-four hour fast. This "
               "ladder is the craft of going further: what to drink, how to keep working through it, what to "
               "do when you feel rough, and — the part nearly everybody gets wrong — how to break a long fast "
               "without wrecking the good of it. It costs nothing; it is the only thing in the school that "
               "saves you money while you do it. If you are pregnant, underweight, diabetic, on medication, "
               "or have any history of disordered eating, this ladder is not for you. Talk to a doctor first."),
        rungs=[
 ("Go sixteen hours with nothing but water, tea or black coffee, and work a normal day inside it.",
  'skill', 'room',
  ["Dinner at seven, nothing until eleven the next morning. Sleep does most of it.",
   "No milk, no sugar, no sweeteners — they end the fast in your head even when they barely do in your body.",
   "Do it on an ordinary working day, not a quiet one."],
  "You have done sixteen hours before; this rung is doing it while life carries on around you. If this is already how you live, do it on purpose today and count it."),
 ("Drink a large glass of water with a pinch of salt in it during a fast.",
  'attention', 'room',
  ["A good pinch of ordinary salt in a pint of water, drunk over an hour.",
   "Do it at the point in the fast where you usually start feeling flat.",
   "Costs nothing and you already have both ingredients."],
  "Most of what people call hunger past about eighteen hours is thirst and salt, not food. This one trick removes most of the headaches people blame fasting for."),
 ("Sit through one wave of hunger without eating, and time how long it lasted.",
  'attention', 'room',
  ["When it arrives, look at the clock and write the time down.",
   "Do something with your hands until it passes, then write that time down too.",
   "Most waves are fifteen to twenty minutes."],
  "Hunger comes in waves and goes again whether you eat or not. Watching one arrive and leave is the single most useful thing on this ladder, because after it you stop believing hunger is an emergency."),
 ("Go eighteen hours, water only.",
  'skill', 'room',
  ["Dinner at seven, nothing until one the next day.",
   "Water, black tea, black coffee, herbal tea. Nothing else.",
   "Plan what you will do at the hour it gets hard — a walk is the best answer."],
  "Eighteen is where sixteen stops being mostly sleep and starts being a decision. The salt water from rung two matters here."),
 ("Take a walk in the middle of a fast rather than sitting through it.",
  'skill', 'out',
  ["Twenty minutes, outside, at the hour you would normally be eating.",
   "Notice that the hunger is quieter while you are moving.",
   "Any weather, any route."],
  "Moving while fasted feels wrong and is not. A walk is the cheapest and fastest way to send a wave of hunger away, and it fills the time the meal used to take."),
 ("Do eighteen hours on three separate days in one week.",
  'attention', 'long',
  ["Three days, with ordinary eating in between. Not consecutive.",
   "Same edges each time so your body knows what is coming.",
   "Write the three days down and tick them off."],
  "Repetition is what makes this comfortable. The third one is always much easier than the first, and it is the rung where fasting stops being an event."),
 ("Break a fast properly: a real meal, eaten slowly, not a feast.",
  'attention', 'room',
  ["Eggs, fish, meat, vegetables, butter. Something you cooked.",
   "Eat it slowly, and stop at comfortably full rather than stuffed.",
   "Nothing sweet as the first thing that goes in."],
  "Almost everybody undoes a good fast in the twenty minutes after it. How you break it matters more than how long it was."),
 ("Go twenty hours, water only.",
  'skill', 'room',
  ["Dinner at seven, nothing until three the next afternoon.",
   "Salt in your water once during the day.",
   "Keep busy through the early afternoon — that is the hard hour."],
  "Twenty hours means one proper meal in a day. That is how a great many people have eaten for most of history and it is not an extreme thing."),
 ("Do a full day on one meal, and make that meal a proper one.",
  'skill', 'room',
  ["One plate, real food, enough of it. Not a small plate.",
   "Eat it at the time that suits your day, and nothing else all day.",
   "Eat until you are properly full — this is not about eating less at the meal."],
  "The mistake here is a small meal, which leaves you hungry and cross and convinced fasting does not suit you. One big honest plate is the rung."),
 ("Go twenty-four hours, from one evening meal to the next.",
  'skill', 'room',
  ["Seven in the evening to seven the next evening.",
   "Water, salt, black tea and coffee. A walk in the afternoon.",
   "Plan the meal at the end before you start, so you are not deciding while hungry."],
  "Evening to evening is much easier than it sounds because you sleep through a third of it and eat on both days. You did one of these in Real food part two — this is doing it deliberately."),
 ("Do twenty-four hours on an ordinary working day, not a quiet one.",
  'courage', 'long',
  ["A normal day of work, people and demands, with nothing to eat in it.",
   "Do not tell everybody. This is not a performance.",
   "Water and salt, and a walk at lunchtime instead of lunch."],
  "Finding out that you can work, think and be civil to people on an empty stomach removes a fear most people carry all their lives."),
 ("Notice what you actually feel when you say you are hungry, and write down three words for it.",
  'attention', 'room',
  ["Do it in the last few hours of a fast.",
   "Bored? Tired? Cold? Sad? Thirsty? Out of habit? Be specific.",
   "Three words, written down."],
  "A good half of what gets called hunger turns out to be something else with a name. Naming it is what lets you answer it properly instead of with food."),
 ("Do twenty-four hours twice in one fortnight.",
  'attention', 'long',
  ["Two full days, a week apart.",
   "Same shape both times so you can compare them.",
   "Write down which was easier and why."],
  "Twice tells you whether the first one was a fluke. For nearly everybody the second is markedly easier, which is the point of doing it."),
 ("Go twenty-eight hours.",
  'skill', 'room',
  ["Evening meal, then through the next day, then sleep, then break it in the morning.",
   "Salt water twice across the day.",
   "Keep the day gentle — light work, walking, nothing heavy."],
  "Past twenty-four hours the hunger usually gets quieter rather than louder, which surprises everybody the first time."),
 ("Sleep through part of a fast, and notice how you sleep.",
  'attention', 'room',
  ["Go to bed inside a fast rather than breaking it at dinner.",
   "Write down in the morning how you slept and how you woke.",
   "Warm room, extra blanket — you will feel the cold more."],
  "Some people sleep beautifully fasted and some sleep badly. Knowing which you are is worth more than any general advice about it."),
 ("Go thirty-two hours.",
  'skill', 'room',
  ["Evening meal to the following morning, through a full day and a night.",
   "Salt and water properly. Do not skip this — it is what keeps your head clear.",
   "Stop if you feel genuinely unwell rather than merely uncomfortable. That is not failure, that is sense."],
  "Knowing the difference between uncomfortable and unwell is the real skill of this ladder. Uncomfortable you can sit through; unwell you eat."),
 ("Do something you would normally need a meal for, while fasted.",
  'courage', 'long',
  ["A long walk, a day out with the children, a hard morning's work, a hill.",
   "Water and salt with you.",
   "Break the fast properly afterwards with a real meal."],
  "This is the rung where the point of the whole thing lands: your day stops being organised around the next meal, and that is a freedom you keep."),
 ("Plan and cook the meal that will break your longest fast, before you start it.",
  'attention', 'kit',
  ["Decide it, shop for it, and have it ready in the fridge.",
   "Meat or fish, vegetables, butter or olive oil. Nothing sweet, nothing from a packet.",
   "Write down the time you will eat it."],
  "Decisions made while hungry are bad decisions. Making this one in advance is what stops thirty-six hours ending in a takeaway."),
 ("Go thirty-six hours, and break it with the meal you planned.",
  'skill', 'room',
  ["Evening meal, a full day, a night, and then breakfast the second morning.",
   "Salt and water throughout, a walk each day, gentle work.",
   "Eat slowly when you break it. Stop at comfortably full."],
  "Thirty-six hours done properly and broken properly is the far end of this ladder. Going further than this is a thing to do with a doctor, not with an app."),
 ("Write down your own rules for fasting, and the ones you will not break.",
  'attention', 'room',
  ["How often, how long, and on which days of your week.",
   "The stop rules: unwell rather than uncomfortable, ill, pregnant, on new medicine.",
   "Who you would tell before a long one."],
  "The ladder ends where Real food ended: with your own written way of doing it rather than somebody else's. Rules you wrote while clear-headed are the ones that hold when you are not."),
])

lib.put(d, 'food.knife', name='Knife and board', size='weeks',
        line='From buttering bread properly to preparing a whole meal, and teaching a younger one.',
        about=("Almost everything that gets called cooking is actually chopping, and almost nobody is ever "
               "taught how. A fortnight of this and a meal takes half as long and costs half as much, because "
               "real ingredients are cheaper than prepared ones and it is the chopping you were paying to "
               "avoid. It also happens to be the safest thing in the kitchen to learn properly and the most "
               "dangerous to pick up by accident."),
        rungs=[
 ("Butter a slice of bread properly, right to the edges.",
  'skill', 'kit',
  ["Soft butter, not fridge-hard. Leave it out for half an hour first.",
   "Spread from the middle outwards, right to every edge and corner.",
   "No tearing the bread."],
  "The smallest possible knife job, and the one that teaches a light hand. Spread a hard butter and you tear the bread; that is the whole lesson in one slice."),
 ("Learn the claw grip, with your fingertips tucked under.",
  'attention', 'with',
  ["Curl the fingers of your holding hand so the knuckles stick out and the fingertips hide behind them.",
   "The flat side of the blade rests against your knuckles and slides along them.",
   "Practise it on a carrot with somebody watching before you speed up at all."],
  "This one grip is why professional cooks can chop fast and still have ten fingers. Learn it before anything else and you never have to unlearn a bad habit."),
 ("Cut a flat side onto a round vegetable first so it cannot roll.",
  'attention', 'home',
  ["Take a slice off one side of the onion, carrot or potato.",
   "Turn it onto that flat side. Now it sits still.",
   "Every round thing gets this treatment, every time."],
  "Rolling vegetables cause most kitchen cuts. This takes two seconds and removes the problem entirely."),
 ("Cut something soft — a banana, a mushroom, a tomato — with the claw grip.",
  'skill', 'home',
  ["Slow. Speed comes from not stopping, never from moving fast.",
   "Let the knife do the work — a sharp knife needs almost no pressure.",
   "Fingertips tucked the whole time."],
  "Soft things show you whether the knife is sharp: if a tomato squashes rather than slices, the knife is blunt and that is more dangerous than a sharp one."),
 ("Peel a vegetable without taking half of it away.",
  'skill', 'kit',
  ["Peeler away from you, long strokes, light pressure.",
   "Turn the vegetable rather than moving your hand about.",
   "Look at the peelings — thin ribbons, not chunks."],
  "The peelings are the evidence. Thick peelings are money in the bin, and on a potato most of the good is just under the skin anyway."),
 ("Chop an onion without help.",
  'skill', 'home',
  ["Top off, leave the root end on — it holds the whole thing together.",
   "Halve it through the root, peel, flat side down.",
   "Cuts towards the root but not through it, then across. It falls into dice."],
  "The onion is the test everybody is measured by, and the root-end trick is the whole secret. Once you can do an onion you can do anything on a board."),
 ("Cut everything for one dish to roughly the same size.",
  'attention', 'home',
  ["Look at the biggest piece and the smallest piece before it goes in the pan.",
   "Same size means everything is cooked at the same moment.",
   "Take an extra minute rather than fixing it later."],
  "This is the actual difference between a decent home cook and a poor one, and it has nothing to do with recipes. Even pieces cook evenly. That is most of cooking."),
 ("Prepare all the vegetables for a whole meal before anything goes in the pan.",
  'skill', 'home',
  ["Everything chopped, in bowls or piles, before the heat goes on.",
   "Board wiped and clear before you start cooking.",
   "It will take longer than you think the first time."],
  "Getting everything ready first is what stops a meal turning into a panic. It also means you can cook things that need your attention rather than only things that wait for you."),
 ("Sharpen a knife, and cut the same vegetable before and after.",
  'attention', 'home',
  ["A cheap steel or a pull-through sharpener, or the back of a ceramic mug in a pinch.",
   "Same angle each stroke, both sides evenly.",
   "Cut a tomato before and cut one after."],
  "A blunt knife needs force, slips, and is how people get cut. A sharp knife is the safe one. Almost every kitchen in the country has only blunt ones."),
 ("Wash, dry and put away your knife and board properly, every time, for a week.",
  'attention', 'home',
  ["By hand, dried immediately, never left in the sink for somebody to reach into.",
   "Never in the dishwasher — it ruins the edge and the handle.",
   "Board scrubbed and stood on its edge to dry."],
  "A knife left in a sink of water is the classic way somebody else gets hurt. This rung is about the person who washes up after you."),
 ("Chop for somebody else who is cooking, at their pace.",
  'kindness', 'with',
  ["Ask what size they want things and do it that way rather than your way.",
   "Keep ahead of them so the pan never waits.",
   "Clear your board as you go."],
  "Being the useful pair of hands in somebody else's kitchen is a social skill as much as a knife one, and it gets you fed in a lot of houses."),
 ("Teach a younger child to chop safely.",
  'kindness', 'with',
  ["Sitting down, at a table, with something soft and a small knife.",
   "The claw grip first, the flat side second, and never anything else until both are automatic.",
   "Your hand over theirs for the first few cuts, then your hands behind your back."],
  "Children are far better at this than adults expect and far safer once shown properly. The ones who are never taught are the ones who get hurt at fifteen."),
])

lib.put(d, 'food.cook', name='Cooking a meal', size='months',
        line='From a cold breakfast to putting a hot meal in front of eight people.',
        about=("Being able to feed yourself and other people well, from real ingredients, without a recipe in "
               "your hand. This is the most immediately useful ladder in the school: it saves real money every "
               "week, it is the practical half of Real food, and a person who can cook is welcome everywhere. "
               "It goes from boiling an egg to a roast and three courses, in about three months of cooking a "
               "few times a week — which you were going to do anyway."),
        rungs=[
 ("Make yourself a cold breakfast and clear it away afterwards.",
  'skill', 'home',
  ["Anything that needs no heat: eggs boiled the night before, yoghurt, fruit, cheese, oatcakes.",
   "Eat it sitting down rather than standing up.",
   "Everything washed, dried and put away before you leave the kitchen."],
  "Clearing away is half of this ladder and the half people skip. A cook who leaves a wreck behind stops getting to cook."),
 ("Make a hot drink safely for yourself and somebody else.",
  'skill', 'home',
  ["Kettle filled above the element, lid down, handle turned in.",
   "Pour slowly, away from you, with the cup on the worktop rather than in your hand.",
   "Ask them how they take it rather than guessing."],
  "The first hot thing you handle. Handle turned in, pour on the worktop — two habits that prevent almost every kitchen scald."),
 ("Boil an egg exactly the way you like it, twice running.",
  'skill', 'home',
  ["Water at a gentle boil, egg in, timer on. Six minutes runny, eight soft, ten hard.",
   "Write down the time that worked.",
   "Do it again two days later using your own number."],
  "Cooking is timing more than anything else. This is the smallest possible lesson in it: same time, same result, every time."),
 ("Read a recipe all the way through before you start.",
  'attention', 'room',
  ["Every line, including the last one, before you touch anything.",
   "Note the bits that need waiting — resting, rising, soaking, marinading.",
   "Check you actually have everything."],
  "Almost every kitchen disaster is a recipe read one line at a time. Two minutes of reading saves the meal where the last step turns out to be 'leave overnight'."),
 ("Get everything out, chopped and weighed before the pan goes on.",
  'attention', 'home',
  ["Every ingredient in its own bowl or pile, in the order it goes in.",
   "Pans out, utensils out, bin within reach.",
   "Only then turn the heat on."],
  "This is how every professional kitchen in the world works and it is why they are calm. Cooking is easy once the chopping is behind you."),
 ("Make beans on toast with both parts ready at the same moment.",
  'attention', 'home',
  ["Work backwards: the toast takes two minutes, the beans take four. Beans first.",
   "Butter on the plate and the table set before either is ready.",
   "Hot food on a warm plate."],
  "The humblest possible lesson in timing two things, and it is exactly the same skill as getting a roast and its vegetables to land together."),
 ("Cook pasta and a sauce and get them together hot.",
  'skill', 'home',
  ["Sauce on first, pasta into properly salted boiling water second.",
   "Taste the pasta a minute before the packet says.",
   "Drain, then straight into the sauce pan and toss — never sauce sitting on top."],
  "Salting the water and finishing the pasta in the sauce are the two things that separate a decent plate of pasta from a sad one, and both are free."),
 ("Fry something without burning it or leaving it raw.",
  'skill', 'home',
  ["Pan properly hot before anything goes in — a drop of water should dance.",
   "Do not crowd the pan. Two batches beats one steamed mess.",
   "Leave it alone. Turn it once, when it lets go of the pan by itself."],
  "Turning things over and over is the commonest mistake there is. A thing that is stuck is not ready to turn; when it is ready, it releases."),
 ("Taste as you go, and change it — more salt, or something sharp.",
  'attention', 'home',
  ["Taste before it goes on the plate, every single time.",
   "Flat and dull usually means salt. Heavy and rich usually means something sharp: lemon, vinegar, mustard.",
   "Add a little, stir, taste again."],
  "This is the rung that makes you a cook rather than a recipe follower. Nobody can taste your food from a page in a book."),
 ("Cook a hot meal for yourself, start to finish.",
  'skill', 'home',
  ["Something real: meat or fish or eggs, a vegetable, something to cook it in.",
   "Everything ready first, taste before serving, sit down to eat it.",
   "Clear the kitchen afterwards."],
  "A whole meal on your own is the middle of this ladder. If this is already routine for you, cook something you have never cooked before and count that."),
 ("Clean as you go, so the kitchen is nearly clear when you sit down.",
  'attention', 'home',
  ["Wash each thing while the next thing cooks.",
   "Bin, cloth and hot soapy water within reach from the start.",
   "The rung is what the kitchen looks like when the food goes on the table."],
  "This is the habit that decides whether cooking feels like a pleasure or a chore, and it costs no extra time at all — only different timing."),
 ("Cook a hot meal for your family.",
  'kindness', 'home',
  ["Something you have cooked before rather than a first attempt.",
   "Ask beforehand what nobody will eat, so you are not surprised.",
   "Plates warm, everything landing together, table laid."],
  "Feeding people is the oldest way there is of saying something you might not say out loud. This rung is worth more than the four above it."),
 ("Cook the same meal again, better.",
  'attention', 'home',
  ["Write down one thing you would change before you forget it.",
   "Cook it again within a fortnight with that one change.",
   "Ask whether they noticed."],
  "Cooking the same thing three times beats cooking three different things. The second and third times are where the skill actually appears."),
 ("Time three things so they are all ready together.",
  'attention', 'home',
  ["Write the times backwards from when you want to eat.",
   "The longest thing goes on first. Everything else fits around it.",
   "One timer per thing if you need it."],
  "This is the whole difficulty of cooking a meal, in one rung. Once you can do this with three things, a Christmas dinner is only the same problem with eight."),
 ("Cook a meal out of whatever happened to be in the house.",
  'skill', 'home',
  ["Look at what you have first, then decide, rather than deciding then shopping.",
   "Eggs, onions, a tin of something and whatever vegetable is going over is a meal.",
   "No shopping trip allowed."],
  "This is where cooking starts saving you real money and real waste. It is also the skill that means you are never stuck."),
 ("Cook for somebody who cannot eat something, and get it right.",
  'kindness', 'home',
  ["Ask exactly what they cannot have, and whether it is a preference or a medical matter.",
   "Read the labels on anything from a packet — it hides in sauces, stock and bread.",
   "Clean board, clean pan, clean knife if it is serious."],
  "Being cooked for safely is rare enough that people remember who did it. Take it seriously and ask rather than assuming."),
 ("Cook a roast, with the vegetables, all ready together.",
  'skill', 'home',
  ["Work backwards from the time you want to eat, on paper.",
   "Meat rests for fifteen or twenty minutes — that is when the vegetables finish and the gravy happens.",
   "A cheap cut cooked slowly beats an expensive one cooked badly."],
  "The roast is the traditional test and it deserves its reputation: six things, one oven, one moment. The resting time is the trick that makes it possible."),
 ("Cook three courses and get them all to the table hot.",
  'skill', 'home',
  ["Pudding made first and left. Starter prepared cold or nearly cooked.",
   "Main the only thing actually happening while people are in the house.",
   "Written plan on the worktop."],
  "Doing the work in advance is the whole answer. Three courses is not three times the cooking, it is one course cooked while people are there and two done that morning."),
 ("Cook a meal for eight people.",
  'skill', 'home',
  ["Choose something that scales and waits: a stew, a curry, a big tray bake, a pot of soup and good bread.",
   "Cook it the day before if you can — most of these are better for it.",
   "Count the plates, forks and chairs before the day."],
  "Numbers are not the hard part. Choosing a dish that forgives being held for half an hour is the whole skill of cooking for a crowd."),
 ("Cook for the whole group at a day out.",
  'kindness', 'out',
  ["A big pot of something, or a fire and something to grill, or a proper picnic you actually made.",
   "Plan for it being cold, wet, and later than intended.",
   "Bring more than you think, and something hot to drink."],
  "Feeding people outdoors is the oldest version of this and the one nobody forgets. It is also the end of the ladder: you can now feed anybody, anywhere."),
])

lib.save(d)
lib.report(d, ['calm.fast','food.knife','food.cook'])
