"""v74: how long each ladder's FIRST rung takes once, read by hand (2026-09-17).
None = several days, or open-ended: it stays out of both daily pools on purpose.
His length rule: 3 and under is the daily target, 5 acceptable, 10 never one of the three."""
MINS = {
 'body.juggle': 3, 'body.skip': 2, 'body.upside': 3, 'body.breath': 2, 'body.strength': 5, 'body.run': 3,
 'body.balance': 3, 'body.ride': 5, 'body.hopping': 2,
 'wild.door1': 60, 'wild.fire': 15, 'wild.wayfind': 3, 'wild.shelter': 45, 'wild.weather': 3, 'wild.living': 15,
 'wild.forage': 30, 'wild.tracks': 20, 'wild.camp': None,
 'water.swim': 5, 'water.cold': 1, 'water.row': 10, 'water.sail': 10, 'water.fish': 20, 'water.pools': 20,
 'fit.pressup': 2, 'fit.situp': 2, 'fit.pullup': 2, 'fit.plank': 2, 'fit.squat': 2, 'fit.lift': 2, 'fit.stretch': 2,
 'fit.sprint': 10, 'fit.body1': 10, 'fit.body2': 5,
 'sky.kite': 15, 'sky.rocket': 10, 'sky.stars': 5, 'sky.birdsflight': 5, 'sky.wind': 2, 'sky.throw': 2,
 'mind.learn1': 15, 'mind.tables': 1, 'mind.cube': 5, 'mind.chess': 5, 'mind.memory': 2, 'mind.mental': 3,
 'mind.codes': 10, 'mind.puzzles': 15, 'mind.findout': 3, 'mind.maps': 5,
 'words.lang': 10, 'words.irish': 5, 'words.read': 5, 'words.books': 3, 'words.hand': 2, 'words.callig': 5,
 'words.poems': 5, 'words.sign': 5,
 'speak.people1': None, 'speak.people2': 5, 'speak.strangers': 3, 'speak.stage': 2, 'speak.listen': 2,
 'speak.hardthing': 5, 'speak.story': 5, 'speak.humour': 3, 'speak.teach': 10, 'speak.sayit': 2, 'speak.connect': 5,
 'make.something1': 10, 'make.wood': 15, 'make.cloth': 3, 'make.knots': 3, 'make.clay': 20, 'make.draw': 6,
 'make.electric': 10, 'make.machines': 5, 'make.photo': 2, 'make.scissors': 1, 'make.crayons': 5,
 'music.play1': 4, 'music.sing': 2, 'music.instrument': 5, 'music.rhythm': 4, 'music.whistle': 3,
 'music.songwrite': 5, 'music.readmusic': 10, 'music.dance': 10, 'music.song': 4,
 'magic.cards': 15, 'magic.coins': 15, 'magic.mentalism': 15, 'magic.mime': 5, 'magic.puppet': 20, 'magic.juggleclub': 10,
 'food.real1': None, 'food.real2': None, 'food.knife': 3, 'food.cook': 10, 'food.bake': 10, 'food.firecook': 30,
 'food.grow': None, 'food.preserve': 60, 'food.host': 5, 'food.kitchen': 1,
 'money.value1': None, 'money.handling': 3, 'money.earn': None, 'money.sell': 20, 'money.run': 5, 'money.invest': None,
 'money.negotiate': 2,
 'beauty.look': 5, 'beauty.proportion': 2, 'beauty.shapes': 2, 'beauty.symmetry': 5, 'beauty.arches': 15, 'beauty.town': 15,
 'classic.logic': None, 'classic.question': 3, 'classic.big': 3, 'classic.stories': 10, 'classic.roots': 5,
 'classic.beautiful': 3, 'classic.think': 10,
 'nerve.asking': 1, 'nerve.walkin': 30, 'nerve.phone': 5, 'nerve.no': 5, 'nerve.onthespot': 5, 'nerve.odd': None,
 'deal.price': 2, 'deal.more': 2, 'deal.phone': 10, 'deal.terms': 3, 'deal.walkaway': None, 'deal.both': 10,
 'belong.town1': 10, 'belong.chair': 5, 'belong.shops': 15, 'belong.cars': 5, 'belong.rooms': 10, 'belong.carry': 2,
 'belong.story': 3,
 'home.works1': 5, 'home.keep': 5, 'home.mend': 5, 'home.tools': 3, 'home.bike': 10, 'home.firstaid': 2,
 'home.engines': 30, 'home.safe': 1,
 'care.animals': None, 'care.younger': 5, 'care.older': 2, 'care.giving': 2, 'care.place': 2, 'care.welcome': 2,
 'care.helping': 2,
 'calm.still1': 2, 'calm.still': 1, 'calm.attention': 10, 'calm.sleep': None, 'calm.hard': None, 'calm.gratitude': 1,
 'calm.fast': None,
 'order.bedroom': 20, 'order.desk': 15, 'order.wardrobe': 10, 'order.broken': 15, 'order.giving': 15,
 'order.digital': 10, 'order.forgotten': 20, 'order.keeping': 15, 'order.ownthings': 2,
}
