"""v74: how long each ladder's FIRST rung takes once, read by hand (2026-09-17).
None = several days, or open-ended: it stays out of both daily pools on purpose.
His length rule: 3 and under is the daily target, 5 acceptable, 10 never one of the three."""
MINS = {
 'body.juggle': 3, 'body.skip': 1, 'body.upside': 2, 'body.breath': 2, 'body.strength': 5, 'body.run': 3,
 'body.balance': 2, 'body.ride': 5, 'body.hopping': 2,
 'wild.door1': 60, 'wild.fire': 10, 'wild.wayfind': 3, 'wild.shelter': 20, 'wild.weather': 3, 'wild.living': 15,
 'wild.forage': 10, 'wild.tracks': 15, 'wild.camp': 30,
 'water.swim': 5, 'water.cold': 1, 'water.row': 10, 'water.sail': 10, 'water.fish': 10, 'water.pools': 5,
 'fit.pressup': 2, 'fit.situp': 2, 'fit.pullup': 2, 'fit.plank': 2, 'fit.squat': 2, 'fit.lift': 2, 'fit.stretch': 2,
 'fit.sprint': 10, 'fit.body1': 10, 'fit.body2': 5,
 'sky.kite': 2, 'sky.rocket': 10, 'sky.stars': 5, 'sky.birdsflight': 5, 'sky.wind': 2, 'sky.throw': 2,
 'mind.learn1': 15, 'mind.tables': 2, 'mind.cube': 5, 'mind.chess': 10, 'mind.memory': 2, 'mind.mental': 3,
 'mind.codes': 10, 'mind.puzzles': 15, 'mind.findout': 3, 'mind.maps': 3,
 'words.lang': 10, 'words.irish': 10, 'words.read': 5, 'words.books': 3, 'words.hand': 3, 'words.callig': 10,
 'words.poems': 10, 'words.sign': 10,
 'speak.people1': None, 'speak.people2': 5, 'speak.strangers': 3, 'speak.stage': 3, 'speak.listen': 2,
 'speak.hardthing': 3, 'speak.story': 3, 'speak.humour': 3, 'speak.teach': 5, 'speak.sayit': 1, 'speak.connect': 3,
 'make.something1': 10, 'make.wood': 15, 'make.cloth': 5, 'make.knots': 5, 'make.clay': 15, 'make.draw': 6,
 'make.electric': 10, 'make.machines': 10, 'make.photo': 3, 'make.scissors': 1, 'make.crayons': 5,
 'music.play1': 4, 'music.sing': 2, 'music.instrument': 5, 'music.rhythm': 4, 'music.whistle': 3,
 'music.songwrite': 5, 'music.readmusic': 3, 'music.dance': 4, 'music.song': 4,
 'magic.cards': 15, 'magic.coins': 5, 'magic.mentalism': 5, 'magic.mime': 5, 'magic.puppet': 15, 'magic.juggleclub': 10,
 'food.real1': None, 'food.real2': None, 'food.knife': 3, 'food.cook': 10, 'food.bake': 10, 'food.firecook': 45,
 'food.grow': 10, 'food.preserve': 15, 'food.host': 5, 'food.kitchen': 1,
 'money.value1': None, 'money.handling': 3, 'money.earn': 5, 'money.sell': 5, 'money.run': 5, 'money.invest': 5,
 'money.negotiate': 5,
 'beauty.look': 3, 'beauty.proportion': 2, 'beauty.shapes': 2, 'beauty.symmetry': 3, 'beauty.arches': 5, 'beauty.town': 3,
 'classic.logic': 5, 'classic.question': 3, 'classic.big': 3, 'classic.stories': 5, 'classic.roots': 5,
 'classic.beautiful': 2, 'classic.think': 5,
 'nerve.asking': 1, 'nerve.walkin': 20, 'nerve.phone': 5, 'nerve.no': 5, 'nerve.onthespot': 2, 'nerve.odd': 5,
 'deal.price': 2, 'deal.more': 5, 'deal.phone': 10, 'deal.terms': 5, 'deal.walkaway': 5, 'deal.both': 10,
 'belong.town1': 10, 'belong.chair': 5, 'belong.shops': 5, 'belong.cars': 10, 'belong.rooms': 30, 'belong.carry': 1,
 'belong.story': 3,
 'home.works1': 5, 'home.keep': 10, 'home.mend': 5, 'home.tools': 5, 'home.bike': 5, 'home.firstaid': 2,
 'home.engines': 5, 'home.safe': 2,
 'care.animals': 5, 'care.younger': 2, 'care.older': 10, 'care.giving': 2, 'care.place': 2, 'care.welcome': 2,
 'care.helping': 2,
 'calm.still1': 2, 'calm.still': 10, 'calm.attention': 10, 'calm.sleep': None, 'calm.hard': 10, 'calm.gratitude': 1,
 'calm.fast': None,
 'order.bedroom': 20, 'order.desk': 15, 'order.wardrobe': 10, 'order.broken': 15, 'order.giving': 15,
 'order.digital': 10, 'order.forgotten': 15, 'order.keeping': 15, 'order.ownthings': 2,
}
