"""Creating order rungs used as Today's extra (regenerated by apply_v79.py from school.json).
(rung n, minutes, note). Doing one as an extra does NOT tick the rung."""
EXTRAS = {
 'order.bedroom': [
  (1, 20, 'Bedside table, chest of drawers, windowsill, the top of the wardrobe you can reach. Everything off, then back only what you picked up in the last seven days. The rest goes where it lives, or into one bag to decide about at the weekend.'),
  (3, 15, 'Every house has one: the box, bag or corner where things wait. Tip it out. Each thing gets one of three answers: bin, give, or a real home. No fourth pile.'),
  (4, 15, 'The bedroom is for sleeping and dressing. The ironing pile, the exercise bike used as a rail, the work bag, the laptop charger: take one of them out and find it a better place tonight. If your bedroom is also where you study or work, give that one corner and keep it there.'),
  (5, 20, 'Look where you never look: under the bed with a torch, along the skirting, into the corners, and the light switch that everybody touches. A damp cloth does all of it. The phone torch is enough light.'),
 ],
 'order.desk': [
  (1, 15, 'Everything off: the pens, the mugs, the post, the charger. Wipe it with a damp cloth until it is bare. Then choose the three things you really use every day, and only those go back; the rest waits in a box on the floor for later. A kitchen table you work or do homework at counts.'),
  (3, 20, 'Put every loose piece of paper into one pile and go through it once, from top to bottom, touching each sheet only once. It goes in the bin, into a folder, or you do what it asks today. Tear anything with a name, address or account number into small pieces before it goes in the bin. A child does the same with school sheets and old drawings, with a grown-up saying what can go.'),
  (5, 15, 'Pick one drawer to hold what you use at the desk: the scissors, a notebook, the tape, the charger you need. Everything else comes out of the drawers and goes to its real place in the house, or goes. With no drawers, a mug or a small box on the desk does the same job.'),
  (6, 15, 'Unplug and put away anything you have not used this month. Coil the rest loosely, hold each one with a bread-bag tie or a strip of paper, and write on it what the cable is for. Keep cables out of the way of chair wheels and feet, never under a rug, and never bent tight or squashed. A child leaves the plugs to a grown-up.'),
  (7, 10, 'Sit as you normally do. Your feet should be flat on the floor, your elbows about level with the desk, and the top of any screen at about eye level. A cushion raises you, a stack of books raises a screen, and a box under the feet helps a child whose feet do not reach. Nothing needs buying.'),
 ],
 'order.wardrobe': [
  (8, 20, 'Thick jumpers and coats in the warm months, light clothes in the cold months. Fold them into a bag, a box or a suitcase and put it under the bed or on a shelf you can reach from the floor. Where the weather is much the same all year, put away the clothes you only wear for rare occasions instead. What is left is only what you can wear this month.'),
  (9, 10, 'Look at what you wear every week and ask what would make mornings easier. A plain jumper that goes with everything, a pair of shoes that do not hurt. Write the list; buying is not today, knowing is. Many things on it can come from a friend, a family member or a clothes swap for free.'),
 ],
 'order.broken': [
  (1, 15, 'Room by room with a pen: the dripping tap, the door that sticks, the lamp with a dead bulb, the drawer that jams, the phone with a cracked screen. Add the things that only half work, like the remote you have to press twice. Just the list tonight. Seeing it all written down is the job.'),
  (10, 20, 'Every home has one thing everybody has stepped round for a year: the loose handle, the wobbly chair, the cupboard door on one hinge. Today, fix that one. A free video search for the exact problem, with the make or model if it has one, usually shows how. If it turns out to need a person with a trade, book them today and count it.'),
 ],
 'order.giving': [
  (1, 15, 'Any bag. Walk the house and fill it with things you have not used in a year: the spare mugs, the gadget still in its box, the clothes that have not fitted for a year. Only your own things, or things everybody in the house agrees about. Tie it and put it by the front door.'),
  (3, 20, 'Open every kitchen cupboard. The third spatula, the mugs nobody picks, the machine used twice, the extra lunch boxes without lids. Unopened food that is still in date can go to a food bank. Anything past its date goes in the bin, not the giving bag.'),
  (4, 15, "Books you will not read again, board games nobody asks for, toys a child has grown out of, the kit from a hobby you have stopped. A child chooses which of their own toys go; nobody gives a child's things away for them. Check games have all their pieces. A friend, a school, a library or a charity shop are all good homes."),
  (5, 15, 'Take everything out. Half-used bottles you do not like go in the bin, and unopened soaps and toiletries can go to a food bank or a shelter. A grown-up checks the dates on every medicine: out-of-date or unwanted medicines go back to a pharmacy, never in the bin or down the sink. Put what stays back out of reach of children.'),
  (8, 10, 'Not the thing you do not want. Something good that you like and hardly use: a book you loved, a good coat, a tool, a game. Pick the person who will use it more and send them a message to say it is theirs. Then hand it over.'),
 ],
 'order.digital': [
  (1, 10, 'Go through your apps page by page. If you cannot remember opening it in the last month, delete it. An app you paid for can usually be downloaded again for no cost from the same account. Many phones can show apps by last use in the settings.'),
  (2, 10, 'Open settings, then notifications, and go down the list. Messages and calls from people stay on. Shops, games, news and anything else that buzzes you: off. You can still open the app whenever you choose.'),
  (3, 10, 'Keep only the apps you use every day on the first page, eight or so. Everything else goes onto the second page or into one folder. The first page is what you see every time you pick the phone up, so make it only what you need.'),
  (5, 10, 'Open your photographs and scroll back one month. Delete the screenshots you no longer need, the blurry ones, and all but the best of the near-identical shots. Many phones have a screenshots album that makes this quick. Check the recently deleted album too, and empty it.'),
  (6, 15, 'Open your email and search for the word unsubscribe. For every newsletter or shop email you never read, open one and press the unsubscribe link at the bottom. Only use the link in emails from companies you know you signed up with. Count to twenty.'),
  (7, 20, 'Start with the oldest. Anything older than a month that needs nothing from you: select it and archive it all at once, which keeps it searchable. Then go through what is left, one email at a time: reply, delete, or archive. The goal is an empty inbox once, tonight.'),
  (8, 15, "Children growing up, family occasions, the people who are gone. Turn on your phone's photo backup (most come with some free space), or copy them onto a computer or a memory stick you already own. Two copies in two different places is safer than one."),
  (10, 10, 'Look through a month of your bank statement, or the subscriptions list in your phone settings. Find the one you forgot about: an app, a channel, a free trial about to start charging. Cancel it today. If somebody else pays for your subscriptions, look through the list with them.'),
  (11, 15, "Open your main email account's security settings. It lists the devices and apps still signed in. Sign out of old phones, old computers, and apps you no longer use. If you see a device you do not recognise, sign it out and change your password."),
 ],
 'order.forgotten': [
  (2, 15, 'Close the blinds and wipe each slat with a damp cloth, or a sock over your hand. Then run a cloth along the top of the curtain rail, where the dust has been sitting for months. For a rail you cannot reach standing on the floor, tie a cloth over the head of a broom; never stand on a chair.'),
  (3, 20, 'Warm water with a drop of washing-up liquid, a cloth, and a dry tea towel or newspaper to finish. Inside first, then outside only where you can reach from the ground. Never lean out of an upstairs window or climb up to reach. Pick a dry day that is not freezing.'),
  (4, 20, 'Take everything out. Wipe the floor of the cupboard, bin what is empty or dried up, and put back only what you use. Never mix two cleaning products, because some, such as bleach, give off dangerous fumes when mixed; keep them all where children cannot get to them. Then wash the bin itself with warm soapy water and dry it.'),
  (5, 20, 'Take everything out of one shelf at a time. Check dates, bin what is past, wipe the shelf, and put back what is good. Do the door shelves last. Warm water and a spoonful of bicarbonate of soda cleans it well, if you have some; plain soapy water works too.'),
  (6, 20, 'One room. Stand on the floor, not on a chair or a step: for high places, use a long-handled duster or a damp cloth over the head of a broom. Dust the light shade with the light switched off and cool. Then go all the way round the skirting boards with a damp cloth.'),
  (8, 15, 'The front door is the first thing you touch coming home. Wipe the door, polish the handle, the letterbox or the doorbell, and sweep the step. In a flat, do your own door and the bit of floor outside it. A bucket of warm soapy water and a cloth is everything.'),
  (9, 15, 'The kettle with white scale inside, the cooker hood filter, the shower head, the vacuum cleaner filter. Pick one, and unplug or switch it off first. For a kettle: half water, half white vinegar, boil, leave an hour, rinse well and boil fresh water twice before using it. Never add any other cleaner to vinegar.'),
  (12, 20, 'Behind the sofa, the back of the cupboard under the stairs, the drawer under the oven, the gap beside the fridge. Pick the one place nobody in the house has looked at in years. Take everything out, clean it, and put back only what belongs there. Twenty minutes, and it is done.'),
 ],
 'order.keeping': [
  (1, 15, 'Keys, glasses, chargers, the post, shoes: the things that always end up on the table. Walk the house and choose one spot for each, close to where you use it. A bowl by the door for keys counts, and so does a shoebox for chargers.'),
  (10, 20, 'Walk every room the way a visitor would see it. Where are the piles back? The chair in the bedroom, the bottom of the stairs, the end of the kitchen counter. Pick the worst one and put it right today.'),
  (11, 15, 'Every home has a spot that always goes wrong: the hall table, the end of the kitchen counter. Watch what lands there. Then give it a new job: a hook for bags, a basket for post, or nothing on it at all.'),
 ],
}
